### ISSUE TITLE
[installation] SUMO install

### ISSUE THREAD

**Issue by cathywu** [flow-project/flow#102]
SUMO wheels install

- Add location of local SUMO install to the instructions and to the script output.
- Resolve the following error:
```
(flow) cathywu:~/flow-public$ python examples/rllab/stabilizing_the_ring.py
/Users/cathywu/anaconda/envs/flow/lib/python3.5/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
Traceback (most recent call last):
  File "examples/rllab/stabilizing_the_ring.py", line 9, in <module>
    from flow.scenarios.loop.gen import CircleGenerator
  File "/Users/cathywu/NotDropbox/flow-public/flow/scenarios/__init__.py", line 4, in <module>
    from flow.scenarios.base_scenario import Scenario
  File "/Users/cathywu/NotDropbox/flow-public/flow/scenarios/base_scenario.py", line 16, in <module>
    from flow.core.traffic_lights import TrafficLights
  File "/Users/cathywu/NotDropbox/flow-public/flow/core/traffic_lights.py", line 3, in <module>
    import traci.constants as tc
ImportError: No module named 'traci'
```

**Comment by AboudyKreidieh** [comment]
Did you run `source activate flow` before you ran the sh file? The issue might be that the pip was not registered in the environment. If not, can you verify if this is the issue (i.e. run it in the environment)?
