### ISSUE TITLE
Installing Ray Library,Running python setup.py develop error

### ISSUE THREAD

**Issue by SJ-L** [flow-project/flow#1073]
**here is the error message:**
```
D:\Anaconda\envs\flow\lib\site-packages\setuptools\command\easy_install.py:147: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
D:\Anaconda\envs\flow\lib\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
running egg_info
writing ray.egg-info\PKG-INFO
writing dependency_links to ray.egg-info\dependency_links.txt
writing entry points to ray.egg-info\entry_points.txt
writing requirements to ray.egg-info\requires.txt
writing top-level names to ray.egg-info\top_level.txt
reading manifest file 'ray.egg-info\SOURCES.txt'
writing manifest file 'ray.egg-info\SOURCES.txt'
running build_ext
error: [WinError 193] %1 is not a valid Win32 application
```

After receiving the error message, I tested Ray with python examples/train.py singleagent_ring,
then I received following error message
```
Traceback (most recent call last):
  File "examples/train.py", line 375, in <module>
    main(sys.argv[1:])
  File "examples/train.py", line 364, in main
    train_rllib(submodule, flags)
  File "examples/train.py", line 194, in train_rllib
    policy_graphs, policy_mapping_fn, policies_to_train)
  File "examples/train.py", line 144, in setup_exps_rllib
    agent_cls = get_agent_class(alg_run)
  File "C:\Users\Shaojie Liu\AppData\Roaming\Python\Python37\site-packages\ray\rllib\utils\deprecation.py", line 116, in _ctor
    error=error,
  File "C:\Users\Shaojie Liu\AppData\Roaming\Python\Python37\site-packages\ray\rllib\utils\deprecation.py", line 42, in deprecation_warning
    raise DeprecationWarning(msg)
DeprecationWarning: `get_agent_class` has been deprecated. Use `ray.rllib.agents.registry::get_trainer_class()` instead.
```

**Comment by lihp11** [comment]
I also met this error.
E:\Users\xxxx\anaconda3\lib\site-packages\setuptools\dist.py:529: UserWarning: Normalizing '0.5.0.dev' to '0.5.0.dev0'
  warnings.warn(tmpl.format(**locals()))
running develop
E:\Users\xxxx\anaconda3\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
E:\Users\xxxx\anaconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running egg_info
writing flow.egg-info\PKG-INFO
writing dependency_links to flow.egg-info\dependency_links.txt
writing requirements to flow.egg-info\requires.txt
writing top-level names to flow.egg-info\top_level.txt
reading manifest file 'flow.egg-info\SOURCES.txt'
adding license file 'LICENSE.md'
writing manifest file 'flow.egg-info\SOURCES.txt'
running build_ext
error: [WinError 2] 系统找不到指定的文件。
