### ISSUE TITLE
[tutorials] rllib tutorial text

### ISSUE THREAD

**Issue by cathywu** [flow-project/flow#108]
The notebook has the following print output, which looks like a spurious error, can we perhaps re-run it? This is the tutorial most likely to be visited, so I'm marking it as high priority.

```
Remote function stop failed with:

Traceback (most recent call last):
  File "/home/aboudy/Documents/ray/python/ray/worker.py", line 862, in _process_task
    *arguments)
  File "/home/aboudy/Documents/ray/python/ray/actor.py", line 245, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/aboudy/Documents/ray/python/ray/tune/trainable.py", line 258, in stop
    self._stop()
  File "/home/aboudy/Documents/ray/python/ray/rllib/ppo/ppo.py", line 274, in _stop
    ev.__ray_terminate__.remote(ev._ray_actor_id.id())
  File "/home/aboudy/Documents/ray/python/ray/actor.py", line 432, in remote
    return self._submit(args, kwargs)
  File "/home/aboudy/Documents/ray/python/ray/actor.py", line 443, in _submit
    dependency=self._actor._ray_actor_cursor)
  File "/home/aboudy/Documents/ray/python/ray/actor.py", line 746, in _actor_method_call
    args = signature.extend_args(function_signature, args, kwargs)
  File "/home/aboudy/Documents/ray/python/ray/signature.py", line 214, in extend_args
    .format(function_name))
Exception: Too many arguments were passed to the function '__ray_terminate__'


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="192.168.1.106:45220")
```

**Comment by kjang96** [comment]
Looking into this; if someone solves this first, ping me so I stop

**Comment by kjang96** [comment]
I had that error until I removed all the `import ipdb; ipdb.set_trace()` from my local ray. After which, I'm unable to reproduce that error. This is what I get instead: 

```
== Status ==
Using FIFO scheduling algorithm.
Result logdir: /Users/kathyjang/ray_results/ring_stabilize
PENDING trials:
 - PPO_WaveAttenuationPOEnv-v0_0:	PENDING

Created LogSyncer for /Users/kathyjang/ray_results/ring_stabilize/PPO_WaveAttenuationPOEnv-v0_0_2018-09-06_13-54-04a3bfu7pz -> 
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 1/4 CPUs, 0/0 GPUs
Result logdir: /Users/kathyjang/ray_results/ring_stabilize
RUNNING trials:
 - PPO_WaveAttenuationPOEnv-v0_0:	RUNNING

TrainingResult for PPO_WaveAttenuationPOEnv-v0_0:
  date: 2018-09-06_13-54-33
  done: true
  episode_len_mean: 100.0
  episode_reward_mean: -618.7483764247104
  experiment_id: 6e288a62b5154bd29d39e429c252e365
  hostname: Kathys-MacBook-Pro.local
  info:
    kl_coefficient: 0.1
    kl_divergence: 1.4180838661559392e-05
    load_time: 0.08836102485656738
    rollouts_time: 5.992580890655518
    sample_throughput: 120.03273903213805
    sgd_time: 1.6662120819091797
    shuffle_time: 0.00016307830810546875
  node_ip: 10.142.36.159
  pid: 13922
  time_this_iter_s: 10.317247867584229
  time_total_s: 10.317247867584229
  timestamp: 1536267273
  timesteps_this_iter: 400
  timesteps_total: 400
  training_iteration: 1
  
Remote function stop failed with:

Traceback (most recent call last):
  File "/Users/kathyjang/research/ray/python/ray/worker.py", line 864, in _process_task
    *arguments)
  File "/Users/kathyjang/research/ray/python/ray/actor.py", line 245, in actor_method_executor
    method_returns = method(actor, *args)
  File "/Users/kathyjang/research/ray/python/ray/tune/trainable.py", line 257, in stop
    self._stop()
  File "/Users/kathyjang/research/ray/python/ray/rllib/ppo/ppo.py", line 274, in _stop
    ev.__ray_terminate__.remote(ev._ray_actor_id.id())
  File "/Users/kathyjang/research/ray/python/ray/actor.py", line 432, in remote
    return self._submit(args, kwargs)
  File "/Users/kathyjang/research/ray/python/ray/actor.py", line 443, in _submit
    dependency=self._actor._ray_actor_cursor)
  File "/Users/kathyjang/research/ray/python/ray/actor.py", line 749, in _actor_method_call
    args = signature.extend_args(function_signature, args, kwargs)
  File "/Users/kathyjang/research/ray/python/ray/signature.py", line 216, in extend_args
    raise Exception("Too many arguments were passed to the function '{}'"
  File "/Users/kathyjang/research/ray/python/ray/signature.py", line 216, in extend_args
    raise Exception("Too many arguments were passed to the function '{}'"
  File "/Users/kathyjang/anaconda/envs/kathy/lib/python3.5/bdb.py", line 48, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/kathyjang/anaconda/envs/kathy/lib/python3.5/bdb.py", line 67, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit


  You can inspect errors by running

      ray.error_info()

  If this driver is hanging, start a new one with

      ray.init(redis_address="10.142.36.159:27387")
  
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/4 CPUs, 0/0 GPUs
Result logdir: /Users/kathyjang/ray_results/ring_stabilize
TERMINATED trials:
 - PPO_WaveAttenuationPOEnv-v0_0:	TERMINATED [pid=13922], 10 s, 400 ts, -619 rew

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/4 CPUs, 0/0 GPUs
Result logdir: /Users/kathyjang/ray_results/ring_stabilize
TERMINATED trials:
 - PPO_WaveAttenuationPOEnv-v0_0:	TERMINATED [pid=13922], 10 s, 400 ts, -619 rew
```

**Comment by eugenevinitsky** [comment]
@cathywu can you post the full trace; the Ray errors are often really high up in the log

**Comment by amztc34283** [comment]
Was this solved?
