### ISSUE TITLE
Running  "python flow/examples/rllab/figure_eight.py" 

### ISSUE THREAD

**Issue by mtgibson2014** [flow-project/flow#109]
There is an issue that says "Memmappingpool" isn't found. I looked a bit into it and it seems like it's trying to find the file from joblib/pool. I don't think joblib.pool.memmappingpool actually exists except here: https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/externals/joblib/pool.py

I'm currently trying to download the repo from the source to see if it works. I tried downloading it via pip and the error still occurred.

**Comment by mtgibson2014** [comment]
compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
Traceback (most recent call last):
  File "flow/examples/rllab/figure_eight.py", line 5, in <module>
    from rllab.algos.trpo import TRPO
  File "/Users/mtgibson/rllab-multiagent/rllab/algos/trpo.py", line 1, in <module>
    from rllab.algos.npo import NPO
  File "/Users/mtgibson/rllab-multiagent/rllab/algos/npo.py", line 3, in <module>
    from rllab.algos.batch_polopt import BatchPolopt
  File "/Users/mtgibson/rllab-multiagent/rllab/algos/batch_polopt.py", line 9, in <module>
    from rllab.sampler import parallel_sampler
  File "/Users/mtgibson/rllab-multiagent/rllab/sampler/parallel_sampler.py", line 2, in <module>
    from rllab.sampler.stateful_pool import singleton_pool, SharedGlobal
  File "/Users/mtgibson/rllab-multiagent/rllab/sampler/stateful_pool.py", line 3, in <module>
    from joblib.pool import MemmappingPool
ImportError: cannot import name 'MemmappingPool'

**Comment by eugenevinitsky** [comment]
Does it fail immediately? Can you attach the full log?

**Comment by maheshmurag** [comment]
Running this works for me on updated flow-project:
![image](https://user-images.githubusercontent.com/5667029/46038735-c4a1ec00-c0c0-11e8-9c63-3df3f89c1df6.png)

Does this warrant closing this issue? @mtgibson2014

**Comment by ashkan-software** [comment]
When I run the grid scenario for a long time, I get:
"traci.exceptions.TraCIException: Departure time in the past."

Here is the full log:
File "/Users/ashkany/Documents/GitHub/flow/examples/rllib/multiagent_exps/DQN/run_this.py", line 199, in <module>
    run_grid(writer, file)
  File "/Users/ashkany/Documents/GitHub/flow/examples/rllib/multiagent_exps/DQN/run_this.py", line 144, in run_grid
    observation_, reward, done, _ = env.step(action)
  File "/Users/ashkany/Documents/GitHub/flow/flow/multiagent_envs/multiagent_env.py", line 87, in step
    self.additional_command()
  File "/Users/ashkany/Documents/GitHub/flow/flow/envs/green_wave_env.py", line 358, in additional_command
    self._reroute_if_final_edge(veh_id)
  File "/Users/ashkany/Documents/GitHub/flow/flow/envs/green_wave_env.py", line 397, in _reroute_if_final_edge
    speed="max")
  File "/Users/ashkany/Documents/GitHub/flow/flow/core/kernel/vehicle/traci.py", line 914, in add
    departSpeed=str(speed))
  File "/Users/ashkany/Documents/GitHub/sumo/tools/traci/_vehicle.py", line 1223, in addFull
    self._connection._sendExact()
  File "/Users/ashkany/Documents/GitHub/sumo/tools/traci/connection.py", line 104, in _sendExact
    raise TraCIException(prefix[1], _RESULTS[prefix[2]], err)
traci.exceptions.TraCIException: Departure time in the past.
Closing connection to TraCI and stopping simulation.

Does anyone have a fix for this?

**Comment by ashkan-software** [comment]
@maheshmurag Did you ever resolve the "Departure time in the past."?
