### ISSUE TITLE
FileNotFoundError when running sugiyama.py

### ISSUE THREAD

**Issue by ZhuangDingyi** [flow-project/flow#321]
Hi, I really appreciate your work. I followed the steps and was ready to run sugiyama.py but got the Error:

Error during start: Traceback (most recent call last):
  File "/home/dingyi/flow-project/flow/flow/scenarios/base_scenario.py", line 827, in generate_net
    edges_dict, conn_dict = self._import_edges_from_net()
  File "/home/dingyi/flow-project/flow/flow/scenarios/base_scenario.py", line 1216, in _import_edges_from_net
    os.path.join(self.cfg_path, self.netfn), parser=parser)
  File "/home/dingyi/anaconda3/envs/flow/lib/python3.5/xml/etree/ElementTree.py", line 1184, in parse
    tree.parse(source, parser)
  File "/home/dingyi/anaconda3/envs/flow/lib/python3.5/xml/etree/ElementTree.py", line 585, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/dingyi/flow-project/flow/flow/scenarios/debug/cfg/sugiyama_20181220-1150491545277849.601907.net.xml'

I have noticed that 2018/12/20-11:50 is exactly the time I run the command. Is there any code that request real-time net.xml files from some external sources?

**Comment by ZhuangDingyi** [comment]
Thanks @eugenevinitsky and sorry for a late update. I tried to install sumo in another way and it did fix the problem. But now I encountered other problems when running examples (SUMO GUI has successfully opened):

`Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown`

I found that _tcpip_ problems appear frequently in SUMO. Do you have any idea about it? Thank you again for your kind response!

**Comment by eugenevinitsky** [comment]
Hi @ZhuangDingyi,
This is an error message that SUMO prints that we have not yet been able to get rid of but does not seem to actually impede any of our run scripts. Does the simulation actually run?

**Comment by ZhuangDingyi** [comment]
Hi @eugenevinitsky, 
Actually, the simulation just got stuck in the first place when I clicked "run" button. The error message jumped out and the terminal started retrying over and over again. I think I need to focused on the SUMO issue in the following days. If I have any updates, I will let you know. Thanks again for your kind response and merry the upcoming Christmas :P

**Comment by eugenevinitsky** [comment]
Hi @ZhuangDingyi, oh can you post the whole error message? We should be able to help you. Merry upcoming Christmas!

**Comment by eugenevinitsky** [comment]
@ZhuangDingyi I see! It looks like your Traci version doesn't match your SUMO version. My recommendation, if you are running this in a conda env, go to the main folder and run `python setup.py develop`. Then, check your .bash_rc, or .bash_profile if you are running a mac and make sure that there are no extraneous definitions defining a path to TRACI such as 
`PYTHONPATH="$HOME/sumo/tools:$PYTHONPATH`

**Comment by yurunsheng1** [comment]
Hi, I meet the same problem when running the examples/sumo/sugiyama.py in **Pycharm**:
```
Error during start: [Errno 2] No such file or directory: '/home/runsheng/codes/flow/flow/core/kernel/scenario/debug/cfg/sugiyama_20190526-2030431558873843.9122386.net.xml'
Retrying in 1 seconds...
/bin/sh: 1: netconvert: not found
Error during start: [Errno 2] No such file or directory: '/home/runsheng/codes/flow/flow/core/kernel/scenario/debug/cfg/sugiyama_20190526-2030431558873843.9122386.net.xml'
Retrying in 1 seconds...
Error during start: [Errno 2] No such file or directory: '/home/runsheng/codes/flow/flow/core/kernel/scenario/debug/cfg/sugiyama_20190526-2030431558873843.9122386.net.xml'
Retrying in 1 seconds...
Error during start: [Errno 2] No such file or directory: '/home/runsheng/codes/flow/flow/core/kernel/scenario/debug/cfg/sugiyama_20190526-2030431558873843.9122386.net.xml'
Retrying in 1 seconds...
Error during start: [Errno 2] No such file or directory: '/home/runsheng/codes/flow/flow/core/kernel/scenario/debug/cfg/sugiyama_20190526-2030431558873843.9122386.net.xml'
Retrying in 1 seconds...
Error during start: [Errno 2] No such file or directory: '/home/runsheng/codes/flow/flow/core/kernel/scenario/debug/cfg/sugiyama_20190526-2030431558873843.9122386.net.xml'
Retrying in 1 seconds...
Traceback (most recent call last):
  File "/home/runsheng/codes/flow/flow/core/kernel/scenario/traci.py", line 523, in generate_net
    edges_dict, conn_dict = self._import_edges_from_net(net_params)
  File "/home/runsheng/codes/flow/flow/core/kernel/scenario/traci.py", line 815, in _import_edges_from_net
    tree = ElementTree.parse(net_path, parser=parser)
  File "/home/runsheng/anaconda3/envs/flow/lib/python3.5/xml/etree/ElementTree.py", line 1184, in parse
    tree.parse(source, parser)
  File "/home/runsheng/anaconda3/envs/flow/lib/python3.5/xml/etree/ElementTree.py", line 585, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/runsheng/codes/flow/flow/core/kernel/scenario/debug/cfg/sugiyama_20190526-2030431558873843.9122386.net.xml'
```

But it is fine when using **Terminal** to run the code. I have no idea why this occurs.......

Thank you!

**Comment by AboudyKreidieh** [comment]
Hi @yurunsheng1 sorry for the late reply! My best guess is pycharm is having difficulty finding the sumo binaries, hence the error message:
```
/bin/sh: 1: netconvert: not found
```
You may want to look into this online, there may be suggestions about how to mix it.

**Comment by buechelmartin** [comment]
Hi @yurunsheng1,

just had the same issue with Pycharm giving the FileNotFoundError while in the terminal everything worked fine. The problem was, as @AboudyKreidieh pointed out, that the binaries of Sumo could not be found within PyCharm. 

The Sumo path was added to the bashrc file by the sumo installation script, but Pycharm does not load this, unlike the terminal. Other than expected, starting PyCharm from the console also did not help.
Since I could not just append the sumo path within PyCharm as done by the export command, my solution was as follows:

- add the PATH environment variable in the Run/Debug configuration of Pycharm.
- paste the FULL paths string to the value field of the PATH environment variable.

To get the full path string my approach was to:
- add these lines on top of the main python file:
import os
print(os.environ['PATH'])
- run this file from the conda env in the terminal
- copy the print output from the terminal

Might not be the most beautiful solution, but now it works.

**Comment by yurunsheng1** [comment]
I will have a try, thank you so much! @buechelmartin @eugenevinitsky @AboudyKreidieh

**Comment by buechelmartin** [comment]
If you initial motivation of using Pycharm was to be able to use the debugger, you might want to know that I wasn't successful yet in using it within the environment python code.
Seems like the way Ray is calling it's workers isn't supported by the Pycharm debugger, at least unless you are using the Professional version. I could not verify this finding for sure though.

Being aware that this might be a new issue, I want to ask the others about hints how they manage to use a debugger working inside the environment code?

Since someone encountering the original error messages when using Pycharm might be highly interested to know if they really want to spend (or lose?) time fixing their Pycharm project, I post it here.

**Comment by zhouhao0605** [comment]
Hi @AboudyKreidieh, I tried sumo-gui successfully but encountered problems with when trying the example. Can you provide any insights? Thanks
 
(base) hao@hao-B360-AORUS-GAMING-3-WIFI:~$ source activate flow
(flow) hao@hao-B360-AORUS-GAMING-3-WIFI:~$ python examples/sumo/sugiyama.py
python: can't open file 'examples/sumo/sugiyama.py': [Errno 2] No such file or directory

**Comment by xiaoToby** [comment]
My log is that:
(flow) wlan-napt-002:flow xiaohongzhi$ python examples/aimsun/sugiyama.py 
^CListening for connection... Traceback (most recent call last):
  File "examples/aimsun/sugiyama.py", line 59, in <module>
    exp = sugiyama_example()
  File "examples/aimsun/sugiyama.py", line 52, in sugiyama_example
    env = TestEnv(env_params, sim_params, scenario, simulator='aimsun')
  File "/Users/xiaohongzhi/flow/flow/envs/base_env.py", line 164, in __init__
    scenario=self.k.scenario, sim_params=sim_params)
  File "/Users/xiaohongzhi/flow/flow/core/kernel/simulation/aimsun.py", line 62, in start_simulation
    return FlowAimsunAPI(port=sim_params.port)
  File "/Users/xiaohongzhi/flow/flow/utils/aimsun/api.py", line 75, in __init__
    self.s = create_client(port, print_status=True)
  File "/Users/xiaohongzhi/flow/flow/utils/aimsun/api.py", line 36, in create_client
    s.connect(('localhost', port))
KeyboardInterrupt
(flow) wlan-napt-002:flow xiaohongzhi$ python examples/rllib/stabilizing_the_ring.py
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-06-29_14-56-15_82061/logs.
Waiting for redis server at 127.0.0.1:12241 to respond...
Waiting for redis server at 127.0.0.1:60833 to respond...
Starting the Plasma object store with 3.435973836 GB memory using /tmp.
I0629 14:56:16.084810 296347072 store.cc:994] Allowing the Plasma store to use up to 3.43597GB of memory.
I0629 14:56:16.089058 296347072 store.cc:1024] Starting object store with directory /tmp and huge page support disabled
Failed to start the UI, you may need to run 'pip install jupyter'.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/3 CPUs, 0/0 GPUs
Memory usage on this node: 6.8/8.6 GB

Created LogSyncer for /Users/xiaohongzhi/ray_results/stabilizing_the_ring/PPO_WaveAttenuationPOEnv-v0_0_2019-06-29_14-56-16_bnosnlr -> 
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 3/3 CPUs, 0/0 GPUs
Memory usage on this node: 6.8/8.6 GB
Result logdir: /Users/xiaohongzhi/ray_results/stabilizing_the_ring
RUNNING trials:
 - PPO_WaveAttenuationPOEnv-v0_0:	RUNNING

2019-06-29 14:56:29,682	WARNING ppo.py:137 -- By default, observations will be normalized with MeanStdFilter
Loading configuration... done.
Success.
 Starting SUMO on port 49927
Loading configuration... done.
2019-06-29 14:56:30,931	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
2019-06-29 14:56:30.940968: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
/anaconda3/envs/flow/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2019-06-29 14:56:33,021	INFO multi_gpu_optimizer.py:74 -- LocalMultiGPUOptimizer devices ['/cpu:0']
Loading configuration... Loading configuration... done.
done.
Success.
Success.
 Starting SUMO on port 49932
 Starting SUMO on port 49933
Loading configuration... Loading configuration... done.
done.
2019-06-29 14:56:50,672	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 1 on CPU (please ignore any CUDA init errors)
2019-06-29 14:56:50,673	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 2 on CPU (please ignore any CUDA init errors)
2019-06-29 14:56:50.674688: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
2019-06-29 14:56:50.675984: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
/anaconda3/envs/flow/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
/anaconda3/envs/flow/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

-----------------------
ring length: 227
v_max: 3.570869368805752
-----------------------

-----------------------
ring length: 231
v_max: 3.761192925277308
-----------------------
Loading configuration... Loading configuration... done.
done.
Success.
Success.
 Starting SUMO on port 49933
 Starting SUMO on port 49932
Loading configuration... Loading configuration... done.
done.

-----------------------
ring length: 252
v_max: 4.759762049824181
-----------------------
Loading configuration... done.
Success.
 Starting SUMO on port 49932
Loading configuration... done.

-----------------------
ring length: 244
v_max: 4.379503211387676
-----------------------
Loading configuration... done.
Success.
 Starting SUMO on port 49933
Loading configuration... done.

-----------------------
ring length: 256
v_max: 4.949804327743507
-----------------------
Loading configuration... done.

-----------------------
ring length: 227
v_max: 3.570869368805752
-----------------------
Success.
 Starting SUMO on port 49933
Loading configuration... done.
Success.
Loading configuration... done.
 Starting SUMO on port 49932
Loading configuration... done.

BUT, i didn't see any sumo program is running...
Why, what should i did ? @ @

**Comment by xiaoToby** [comment]
^CTraceback (most recent call last):
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/monitor.py", line 379, in <module>
    monitor.run()
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/monitor.py", line 320, in run
    time.sleep(ray._config.heartbeat_timeout_milliseconds() * 1e-3)
KeyboardInterrupt
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0629 15:03:27.765766 1555912128 raylet_extension.cc:66]  Check failed: _s.ok() [RayletClient] Failed to get a task from raylet.: IOError: [RayletClient] Raylet connection closed.
*** Check failure stack trace: ***
Fatal Python error: Aborted

Stack (most recent call first):
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 944 in _get_next_task_from_local_scheduler
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 961 in main_loop
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/workers/default_worker.py", line 107 in <module>
Traceback (most recent call last):
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/workers/default_worker.py", line 107, in <module>
Traceback (most recent call last):
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/workers/default_worker.py", line 107, in <module>
    ray.worker.global_worker.main_loop()
    ray.worker.global_worker.main_loop()
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 962, in main_loop
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 962, in main_loop
    self._wait_for_and_process_task(task)
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 919, in _wait_for_and_process_task
    self._wait_for_and_process_task(task)
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 919, in _wait_for_and_process_task
    self._process_task(task, execution_info)
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 820, in _process_task
    self._process_task(task, execution_info)
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 820, in _process_task
    self.actors[key], *arguments)
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/function_manager.py", line 713, in actor_method_executor
    self.actors[key], *arguments)
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/function_manager.py", line 713, in actor_method_executor
    method_returns = method(actor, *args)
    method_returns = method(actor, *args)
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 368, in sample
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 368, in sample
    batches = [self.input_reader.next()]
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/offline/input_reader.py", line 25, in next
    batches = [self.input_reader.next()]
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/offline/input_reader.py", line 25, in next
    batches = [self.sampler.get_data()]
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 64, in get_data
    batches = [self.sampler.get_data()]
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 64, in get_data
    item = next(self.rollout_provider)
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 282, in _env_runner
    item = next(self.rollout_provider)
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 267, in _env_runner
    preprocessors, obs_filters, unroll_length, pack, callbacks)
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 406, in _process_observations
    async_vector_env.send_actions(actions_to_send)
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/env/async_vector_env.py", line 248, in send_actions
    resetted_obs = async_vector_env.try_reset(env_id)
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/env/async_vector_env.py", line 252, in try_reset
    self.vector_env.vector_step(action_vector)
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/env/vector_env.py", line 89, in vector_step
    obs, rew, done, info = self.envs[i].step(actions[i])
  File "/Users/xiaohongzhi/flow/flow/envs/base_env.py", line 325, in step
    return {_DUMMY_AGENT_ID: self.vector_env.reset_at(env_id)}
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/env/vector_env.py", line 83, in reset_at
    return self.envs[index].reset()
  File "/Users/xiaohongzhi/flow/flow/envs/loop/wave_attenuation.py", line 209, in reset
    self.k.vehicle.get_controlled_ids(), accel)
  File "/Users/xiaohongzhi/flow/flow/core/kernel/vehicle/traci.py", line 880, in apply_acceleration
    observation = super().reset()
  File "/Users/xiaohongzhi/flow/flow/envs/base_env.py", line 533, in reset
    observation, _, _, _ = self.step(rl_actions=None)
  File "/Users/xiaohongzhi/flow/flow/envs/base_env.py", line 325, in step
    self.kernel_api.vehicle.slowDown(vid, next_vel, 1e-3)
  File "/Users/xiaohongzhi/sumo/tools/traci/_vehicle.py", line 958, in slowDown
    self.k.vehicle.get_controlled_ids(), accel)
  File "/Users/xiaohongzhi/flow/flow/core/kernel/vehicle/traci.py", line 880, in apply_acceleration
    self._connection._beginMessage(
KeyboardInterrupt
    self.kernel_api.vehicle.slowDown(vid, next_vel, 1e-3)
  File "/Users/xiaohongzhi/sumo/tools/traci/_vehicle.py", line 962, in slowDown
    self._connection._sendExact()
  File "/Users/xiaohongzhi/sumo/tools/traci/connection.py", line 95, in _sendExact
    result = self._recvExact()
  File "/Users/xiaohongzhi/sumo/tools/traci/connection.py", line 74, in _recvExact
    t = self._socket.recv(4 - len(result))
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/xiaohongzhi/flow/flow/envs/base_env.py", line 658, in terminate
    self.k.close()
  File "/Users/xiaohongzhi/flow/flow/core/kernel/kernel.py", line 108, in close
    self.simulation.close()
  File "/Users/xiaohongzhi/flow/flow/core/kernel/simulation/traci.py", line 64, in close
    self.kernel_api.close()
  File "/Users/xiaohongzhi/sumo/tools/traci/connection.py", line 355, in close
    self._sendExact()
  File "/Users/xiaohongzhi/sumo/tools/traci/connection.py", line 101, in _sendExact
    prefix = result.read("!BBB")
  File "/Users/xiaohongzhi/sumo/tools/traci/storage.py", line 37, in read
    return struct.unpack(format, self._content[oldPos:self._pos])
struct.error: unpack requires a bytes object of length 3
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0629 15:03:28.852365 1682982336 raylet_extension.cc:190]  Check failed: _s.ok() [RayletClient] Failed to wait for objects.: IOError: [RayletClient] Raylet connection closed.
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0629 15:03:28.852478 1776240064 raylet_extension.cc:66]  Check failed: _s.ok() [RayletClient] Failed to get a task from raylet.: IOError: [RayletClient] Raylet connection closed.
*** Check failure stack trace: ***
*** Check failure stack trace: ***
Fatal Python error: Aborted

Stack (most recent call first):
  File "/anaconda3/envs/flowFatal Python error: /Abortedl

ibStack (most recent call first):
/python3.5/  File site-packages/ray/wor"k/earn.apcyo"nda3/envs/flo, line w2485/ in lwiabi/tp
y  File thon3.5/site-"p/aacnkaacgoensd/ar3a/ye/nwvosr/kfelro.wp/yl"ib/pythoWARNING: Logging before InitGoogleLogging() is written to STDERR
n, line 3F0629 15:03:28.852989 1589392832 raylet_extension.cc:190]  Check failed: _s.ok() [RayletClient] Failed to wait for objects.: IOError: [RayletClient] Raylet connection closed.
.9445 in /site-pac_kgaegte_sn/erxaty_/tralslki_bf/roopmt_ilmoiczaelr_ss/crhoeldluoluetr*** Check failure stack trace: ***
.
p  File y""/anaconda3/, line e26n in vs/flow/licbo/lpyltehcoFatal Python error: tn_Aborted3s

.a5m/pslietse
Stack (most recent call first):
-packages/r  File a"y//aw  File noarckoenrd.ap3y/"e, line n961v in sm/afilno_wl/oloipb"
//payntahcoonn3d.a5  File /3s/ietnev-sp/afclkoawg/elsi/br/apyy/trhlo"n/l3ai.nb5a//cosopinttdieam-3ip/zaeecrnskv/asmg/ueflslt/oirw_a/ygl/piwubo_/ropkpyettrih.mopinyz3"e.r5./psyi"te-pac, line k2485a in ge, line s125/ in rsatywe/apw
io  File tr
"k/earnsa/cdoenfda  File au3l/te_nwvosr/kfl"/anaconda3/envs/ofwl/olwe/ilbir/b.p/pypyty"htohno3n.35./5s/istiet-e, line p-107ap in acckkaaggeess//rraayy/</rmtlouldniuebl//era>ag
ye_nttrsi/aplp_oe/xpepcou.tpoyr".p, line y101" in , line 199 in _train
  File "/gaenta_cnoenxdta_3a/veanivlsa/bflleo_wt/rliiabl
/  File "/payntahcoonn3d.a53/s/ite-packages/ray/tune/trainable.py", line e146n in vtsr/afilno
w/lib/python3  File .5"//saintaec-opnadcak3a/geensv/sr/afyl/otwu/nlei/bt/rpiyatlh_ornu3n.5n/site-packages/ray/rllib/agenetrs./payg"ent.py", line 259 in , line 279 in t_rpariocne
s  File s_"e/vaennatcso
nda3/envs/  File f"l/oawn/alciobn/dpay3t/heonnv3s./5f/lsoiwt/el-ipba/cpkyatgheosn/3r.a5y//sfiutnec-tpiaocnk_amgaensa/greary./ptyu"ne, line /713t in raicatlo_rr_umnentehro.dp_ye"xecutor
  File "/, line a118n in aconda3/envss/tfelpo
w/lib/python3  File .5/site-packages/ray/wor"k/earn.apcyo"n, line d820a in 3_/pernovcse/sfsl_otwa/slki
b  File /"p/yatnhaocno3n.d5a/3s/ietnev-sp/afclkoawg/elsi/br/apyy/tthuonne3/.t5u/nsei.tpey-"packages/ray, line /108w in orker.py"run_experi, line m919e in n_twsa
it_for_and_p  File rocess_task
  File "/anaco"nedxaa3m/pelnevss//rfllloiwb//lsitba/bpiyltihzoinn3g._5t/hsei_trei-npga.cpkya"ges/ray/wor, line k140e in r.py"<mod, line u962l in em>a
in_loop
  File "/anaconda3/envs/flow/lib/python3.5/site-packages/ray/workers/default_worker.py", line 107 in <module>
Abort trap: 6
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown.

This is other log when i type Control+C.

**Comment by buechelmartin** [comment]
@zhouhao0605: looks like your sumo path is not in your python path and you dont call the full, correct path.

@xiaoToby : check out the tutorial about visualization. per default, sumo is not rendered since this takes too long during training. you can run the visualizer from the checkpoints later. thats all in the tutorials
