### ISSUE TITLE
Unable to launch ray cluster with Flow

### ISSUE THREAD

**Issue by cathywu** [flow-project/flow#353]
**Choose an option**
This is a: 
- [ ] Question
- [ ] Feature request
- [x] Bug report

**Describe the issue**
A clear and concise description of what the bug/question/feature request is.

I'm not successfully able to launch a ray cluster using our autoscaling script. Is the script and/or docker image up-to-date? I noticed that the autoscaling script has the following line, which indicates a old branch (please confirm) @eugenevinitsky :

```
    - cd ray && git fetch eugene_upstream && git checkout eugene_upstream/master && git pull eugene_upstream master
```

**To Reproduce**
Leave empty if not applicable.

Modify `scripts/ray_autoscale.yaml` with local directory and custom cluster name.

1. File in which error occurred.  `scripts/ray_autoscale.yaml`
2. Exact command that was run that caused the error to occur. `ray create-or-update scripts/ray_autoscale.yaml`
3. Please attach the full error output log. 

```
$ ray create-or-update scripts/ray_autoscale.yaml
This will restart cluster services [y/N]: y
Updating files on head node...
NodeUpdater: Updating i-0b11da8b956bb811a to eae005ad89c91c8380badb0d380c273f3991279d, logging to (console)
NodeUpdater: Waiting for IP of i-0b11da8b956bb811a...
NodeUpdater: Waiting for SSH to i-0b11da8b956bb811a...
NodeUpdater: Syncing /Users/cathywu/NotDropbox/flow-public/.git/refs/heads/repro to /tmp/path...
building file list ... done

sent 82 bytes  received 20 bytes  68.00 bytes/sec
total size is 41  speedup is 0.40
NodeUpdater: Syncing /var/folders/tj/ndqgsv0n3n93fqzq2y8gfv280000gn/T/ray-bootstrap-3ogcehga to ~/ray_bootstrap_config.yaml...
building file list ... done
ray-bootstrap-3ogcehga

sent 941 bytes  received 60 bytes  400.40 bytes/sec
total size is 1924  speedup is 1.92
NodeUpdater: Syncing /Users/cathywu/.ssh/ray-autoscaler_us-west-1.pem to ~/ray_bootstrap_key.pem...
building file list ... done

sent 105 bytes  received 20 bytes  35.71 bytes/sec
total size is 1670  speedup is 13.36
NodeUpdater: running

	cd flow && git fetch && git checkout `cat /tmp/path`

 on 54.153.85.227...
fatal: reference is not a tree: 6ee1ec10d57dedbc42e033d814190b8fbe8fa981
NodeUpdater: Error updating (Exit Status 128)

	ssh -o ConnectTimeout=120s -o StrictHostKeyChecking=no -i /Users/cathywu/.ssh/ray-autoscaler_us-west-1.pem ubuntu@54.153.85.227 bash --login -c 'set -i || true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && cd flow && git fetch && git checkout `cat /tmp/path`'

See (console) for remote logs.
Process NodeUpdaterProcess-1:
Traceback (most recent call last):
  File "/Users/cathywu/anaconda/envs/flow20181224/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Users/cathywu/anaconda/envs/flow20181224/lib/python3.5/site-packages/ray/autoscaler/updater.py", line 104, in run
    raise e
  File "/Users/cathywu/anaconda/envs/flow20181224/lib/python3.5/site-packages/ray/autoscaler/updater.py", line 89, in run
    self.do_update()
  File "/Users/cathywu/anaconda/envs/flow20181224/lib/python3.5/site-packages/ray/autoscaler/updater.py", line 176, in do_update
    self.ssh_cmd(cmd, verbose=True)
  File "/Users/cathywu/anaconda/envs/flow20181224/lib/python3.5/site-packages/ray/autoscaler/updater.py", line 244, in ssh_cmd
    stderr=redirect or self.stderr)
  File "/Users/cathywu/anaconda/envs/flow20181224/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', '-o', 'ConnectTimeout=120s', '-o', 'StrictHostKeyChecking=no', '-i', '/Users/cathywu/.ssh/ray-autoscaler_us-west-1.pem', 'ubuntu@54.153.85.227', "bash --login -c 'set -i || true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && cd flow && git fetch && git checkout `cat /tmp/path`'"]' returned non-zero exit status 128
Updating 54.153.85.227 failed
```

**Expected behavior**
Leave empty if not applicable.

Created cluster without error messages.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OS X El Capitan
 - Commit number of flow [run git log and copy the commit number] close to `61353ceaa11e21276941603a35ad52f6f7fe55d6`
 - Version [run python -c "import flow; print(flow.__version__)"]: 0.2.1
 Leave empty if not applicable.

**Additional context**

**Comment by cathywu** [comment]
The issue was that the autoscaling script doesn't naturally support branches from forks of the flow repo. I found a workaround, so I am closing this. On ray, I went in and manually updated ray after a successful launch. We may want to update the AMI.
