### ISSUE TITLE
'Worker' object has no attribute 'task_index'

### ISSUE THREAD

**Issue by KidTrunks** [flow-project/flow#369]
Upon running experiments of tutorial 02, the following errors were encountered:

== Status ==
Using FIFO scheduling algorithm.

Created LogSyncer for /home/python/ray_results/ring_stabilize/PPO_WaveAttenuationPOEnv-v0_0_2019-01-04_20-49-3532b24nc8 ->
Error stopping runner - retrying...
Traceback (most recent call last):
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 116, in start_trial
self._start_trial(trial, checkpoint_obj)
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 62, in _start_trial
trial.runner = self._setup_runner(trial)
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 50, in _setup_runner
return cls.remote(config=trial.config, logger_creator=logger_creator)
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/actor.py", line 571, in remote
return self._submit(args=args, kwargs=kwargs)
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/actor.py", line 633, in _submit
resources=resources)
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 662, in submit_task
task_index = self.task_index
AttributeError: 'Worker' object has no attribute 'task_index'
Worker ip unknown, skipping log sync for /home/python/ray_results/ring_stabilize/PPO_WaveAttenuationPOEnv-v0_0_2019-01-04_20-49-3532b24nc8
Created LogSyncer for /home/python/ray_results/ring_stabilize/PPO_WaveAttenuationPOEnv-v0_0_2019-01-04_20-49-37o02dfzew ->
Error starting runner, aborting!
Traceback (most recent call last):
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 116, in start_trial
self._start_trial(trial, checkpoint_obj)
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 62, in _start_trial
trial.runner = self._setup_runner(trial)
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 50, in _setup_runner
return cls.remote(config=trial.config, logger_creator=logger_creator)
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/actor.py", line 571, in remote
return self._submit(args=args, kwargs=kwargs)
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/actor.py", line 633, in _submit
resources=resources)
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 662, in submit_task
task_index = self.task_index
AttributeError: 'Worker' object has no attribute 'task_index'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 123, in start_trial
self._start_trial(trial)
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 62, in _start_trial
trial.runner = self._setup_runner(trial)
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 50, in _setup_runner
return cls.remote(config=trial.config, logger_creator=logger_creator)
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/actor.py", line 571, in remote
return self._submit(args=args, kwargs=kwargs)
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/actor.py", line 633, in _submit
resources=resources)
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 662, in submit_task
task_index = self.task_index
AttributeError: 'Worker' object has no attribute 'task_index'
Worker ip unknown, skipping log sync for /home/python/ray_results/ring_stabilize/PPO_WaveAttenuationPOEnv-v0_0_2019-01-04_20-49-37o02dfzew
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 2/2 CPUs, 0/0 GPUs
Result logdir: /home/python/ray_results/ring_stabilize
ERROR trials:

PPO_WaveAttenuationPOEnv-v0_0:	ERROR, 2 failures: /home/python/ray_results/ring_stabilize/PPO_WaveAttenuationPOEnv-v0_0_2019-01-04_20-49-37o02dfzew/error_2019-01-04_20-49-37.txt
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 2/2 CPUs, 0/0 GPUs
Result logdir: /home/python/ray_results/ring_stabilize
ERROR trials:

PPO_WaveAttenuationPOEnv-v0_0:	ERROR, 2 failures: /home/python/ray_results/ring_stabilize/PPO_WaveAttenuationPOEnv-v0_0_2019-01-04_20-49-37o02dfzew/error_2019-01-04_20-49-37.txt
Traceback (most recent call last):
File "", line 17, in 
File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/tune.py", line 118, in run_experiments
raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_WaveAttenuationPOEnv-v0_0])

Please let me know how the 2 failures can be fixed.

Thanks!

**Comment by KidTrunks** [comment]
Upon running experiments of tutorial 02, the following errors were encountered:

== Status ==
Using FIFO scheduling algorithm.


Created LogSyncer for /home/python/ray_results/ring_stabilize/PPO_WaveAttenuationPOEnv-v0_0_2019-01-04_20-49-3532b24nc8 -> 
Error stopping runner - retrying...
Traceback (most recent call last):
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 116, in start_trial
    self._start_trial(trial, checkpoint_obj)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 62, in _start_trial
    trial.runner = self._setup_runner(trial)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 50, in _setup_runner
    return cls.remote(config=trial.config, logger_creator=logger_creator)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/actor.py", line 571, in remote
    return self._submit(args=args, kwargs=kwargs)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/actor.py", line 633, in _submit
    resources=resources)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 662, in submit_task
    task_index = self.task_index
AttributeError: 'Worker' object has no attribute 'task_index'
Worker ip unknown, skipping log sync for /home/python/ray_results/ring_stabilize/PPO_WaveAttenuationPOEnv-v0_0_2019-01-04_20-49-3532b24nc8
Created LogSyncer for /home/python/ray_results/ring_stabilize/PPO_WaveAttenuationPOEnv-v0_0_2019-01-04_20-49-37o02dfzew -> 
Error starting runner, aborting!
Traceback (most recent call last):
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 116, in start_trial
    self._start_trial(trial, checkpoint_obj)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 62, in _start_trial
    trial.runner = self._setup_runner(trial)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 50, in _setup_runner
    return cls.remote(config=trial.config, logger_creator=logger_creator)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/actor.py", line 571, in remote
    return self._submit(args=args, kwargs=kwargs)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/actor.py", line 633, in _submit
    resources=resources)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 662, in submit_task
    task_index = self.task_index
AttributeError: 'Worker' object has no attribute 'task_index'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 123, in start_trial
    self._start_trial(trial)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 62, in _start_trial
    trial.runner = self._setup_runner(trial)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 50, in _setup_runner
    return cls.remote(config=trial.config, logger_creator=logger_creator)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/actor.py", line 571, in remote
    return self._submit(args=args, kwargs=kwargs)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/actor.py", line 633, in _submit
    resources=resources)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 662, in submit_task
    task_index = self.task_index
AttributeError: 'Worker' object has no attribute 'task_index'
Worker ip unknown, skipping log sync for /home/python/ray_results/ring_stabilize/PPO_WaveAttenuationPOEnv-v0_0_2019-01-04_20-49-37o02dfzew
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 2/2 CPUs, 0/0 GPUs
Result logdir: /home/python/ray_results/ring_stabilize
ERROR trials:
 - PPO_WaveAttenuationPOEnv-v0_0:	ERROR, 2 failures: /home/python/ray_results/ring_stabilize/PPO_WaveAttenuationPOEnv-v0_0_2019-01-04_20-49-37o02dfzew/error_2019-01-04_20-49-37.txt

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 2/2 CPUs, 0/0 GPUs
Result logdir: /home/python/ray_results/ring_stabilize
ERROR trials:
 - PPO_WaveAttenuationPOEnv-v0_0:	ERROR, 2 failures: /home/python/ray_results/ring_stabilize/PPO_WaveAttenuationPOEnv-v0_0_2019-01-04_20-49-37o02dfzew/error_2019-01-04_20-49-37.txt

Traceback (most recent call last):
  File "<stdin>", line 17, in <module>
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/tune.py", line 118, in run_experiments
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_WaveAttenuationPOEnv-v0_0])
>>> 

Please let me know how the 2 failures can be fixed.

Thanks!

**Comment by AboudyKreidieh** [comment]
@KidTrunks thank you for bringing this up! I’ll look into it and get back to you shortly.

**Comment by fywu85** [comment]
@KidTrunks Which version of Ray are you currently using?

**Comment by KidTrunks** [comment]
@fywu85 I am currently using Ubuntu version 18.04.1.
Ray Version -  0.6.0
I Installed ray by-  "pip install -U ray"

Could it be a compatibility issue? Would I need to downgrade Ray or Ubuntu?

Thanks for your help.

**Comment by KidTrunks** [comment]
Hi, I think this may have been caused by a ray error.

During step 4 Running RL experiments in RAY:

>>> N_CPUS = 2
>>> N_ROLLOUTS = 1
>>> ray.init(redirect_output=True, num_cpus=CPUS)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'CPUS' is not defined
>>> ray.init(redirect_output=True, num_cpus=N_CPUS)
Process STDOUT and STDERR is being redirected to /tmp/raylogs/.
Waiting for redis server at 127.0.0.1:26152 to respond...
Waiting for redis server at 127.0.0.1:62596 to respond...
Starting the Plasma object store with 4.00 GB memory.
Starting local scheduler with the following resources: {'GPU': 0, 'CPU': 2}.

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui60086.ipynb?token=69501fa827a8629f1a8091b39fdaf4414fe3cc8a4e1d9718
======================================================================

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 1866, in init
    use_raylet=use_raylet)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 1727, in _init
    use_raylet=use_raylet)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 2165, in connect
    worker.redis_client.hmset(b"Drivers:" + worker.worker_id, driver_info)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/utils.py", line 387, in _wrapper
    return orig_attr(*args, **kwargs)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/redis/client.py", line 2636, in hmset
    return self.execute_command('HMSET', name, *items)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/redis/client.py", line 754, in execute_command
    connection.send_command(*args)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/redis/connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/redis/connection.py", line 659, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/redis/connection.py", line 124, in encode
    "byte, string or number first." % typename)
redis.exceptions.DataError: Invalid input of type: 'NoneType'. Convert to a byte, string or number first.

It seems like I may need to convert this line into a string? 

>>> ray.init(redirect_output=True, num_cpus=CPUS)

Does anyone know how to do that?

Thanks!

**Comment by KidTrunks** [comment]
Error was solved after changing:
ray.init(redirect_output=True, num_cpus=CPUS)
to
ray.init(num_cpus=CPUS)
