### ISSUE TITLE
Tutorial03 (rllib) fails to run due to Exception: Unknown config parameter `sgd_batchsize`

### ISSUE THREAD

**Issue by ae137** [flow-project/flow#400]
**Choose an option**
This is a: 
- [ ] Question
- [ ] Feature request
- [X] Bug report

**Describe the issue**
I wanted to run the rllib tutorial from https://github.com/flow-project/flow/blob/master/tutorials/tutorial03_rllib.ipynb . However, it fails with the following error message (in 4.4 Running Experiments)

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/2 CPUs, 0/0 GPUs
Memory usage on this node: 2.1/4.1 GB

Created LogSyncer for /home/andreas/ray_results/ring_stabilize/PPO_WaveAttenuationPOEnv-v0_0_2019-02-03_14-36-014h1eblcc -> 
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 2/2 CPUs, 0/0 GPUs
Memory usage on this node: 2.1/4.1 GB
Result logdir: /home/andreas/ray_results/ring_stabilize
RUNNING trials:
 - PPO_WaveAttenuationPOEnv-v0_0:	RUNNING

Error processing event.
Traceback (most recent call last):
  File "/home/andreas/ray/python/ray/tune/trial_runner.py", line 261, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/andreas/ray/python/ray/tune/ray_trial_executor.py", line 211, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/andreas/ray/python/ray/worker.py", line 2386, in get
    raise value
ray.worker.RayTaskError: ray_PPOAgent:train() (pid=9977, host=andreas-kubuntu1804)
  File "/home/andreas/ray/python/ray/rllib/agents/agent.py", line 244, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/andreas/ray/python/ray/tune/trainable.py", line 87, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/andreas/ray/python/ray/rllib/agents/agent.py", line 304, in _setup
    self._allow_unknown_subkeys)
  File "/home/andreas/ray/python/ray/tune/util.py", line 63, in deep_update
    raise Exception("Unknown config parameter `{}` ".format(k))
Exception: Unknown config parameter `sgd_batchsize`

Replacing 
`config["sgd_batchsize"] = min(16 * 1024, config["timesteps_per_batch"])  # stochastic gradient descent`
by
`config["train_batch_size"] = 128`
and removing 
config["timesteps_per_batch"] = HORIZON * N_ROLLOUTS  # batch size
I receive another error message as follows:

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/2 CPUs, 0/0 GPUs
Memory usage on this node: 2.4/4.1 GB

Created LogSyncer for /home/andreas/ray_results/ring_stabilize/PPO_WaveAttenuationPOEnv-v0_0_2019-02-03_14-52-21k54fo275 -> 
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 2/2 CPUs, 0/0 GPUs
Memory usage on this node: 2.4/4.1 GB
Result logdir: /home/andreas/ray_results/ring_stabilize
RUNNING trials:
 - PPO_WaveAttenuationPOEnv-v0_0:	RUNNING

Error processing event.
Traceback (most recent call last):
  File "/home/andreas/ray/python/ray/tune/trial_runner.py", line 261, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/andreas/ray/python/ray/tune/ray_trial_executor.py", line 211, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/andreas/ray/python/ray/worker.py", line 2386, in get
    raise value
ray.worker.RayTaskError: ray_PPOAgent:train() (pid=10279, host=andreas-kubuntu1804)
  File "/home/andreas/anaconda3/envs/flow/lib/python3.5/site-packages/gym/envs/registration.py", line 143, in spec
    return self.env_specs[id]
KeyError: 'WaveAttenuationPOEnv-v0'

During handling of the above exception, another exception occurred:

ray_PPOAgent:train() (pid=10279, host=andreas-kubuntu1804)
  File "/home/andreas/ray/python/ray/rllib/agents/agent.py", line 244, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/andreas/ray/python/ray/tune/trainable.py", line 87, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/andreas/ray/python/ray/rllib/agents/agent.py", line 312, in _setup
    self._init()
  File "/home/andreas/ray/python/ray/rllib/agents/ppo/ppo.py", line 75, in _init
    self.env_creator, self._policy_graph)
  File "/home/andreas/ray/python/ray/rllib/agents/agent.py", line 413, in make_local_evaluator
    config["local_evaluator_tf_session_args"]
  File "/home/andreas/ray/python/ray/rllib/agents/agent.py", line 553, in _make_evaluator
    output_creator=output_creator)
  File "/home/andreas/ray/python/ray/rllib/evaluation/policy_evaluator.py", line 217, in __init__
    self.env = env_creator(env_context)
  File "/home/andreas/flow/flow/utils/registry.py", line 106, in create_env
    return gym.envs.make(env_name)
  File "/home/andreas/anaconda3/envs/flow/lib/python3.5/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/andreas/anaconda3/envs/flow/lib/python3.5/site-packages/gym/envs/registration.py", line 118, in make
    spec = self.spec(id)
  File "/home/andreas/anaconda3/envs/flow/lib/python3.5/site-packages/gym/envs/registration.py", line 153, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: WaveAttenuationPOEnv-v0

Could it be that the installation instructions point to a wrong version of rllib or that the assignment of env_names and gym_names is not correct in the notebook?

**To Reproduce**
After installing flow and rllib acording to the installation manual on https://flow.readthedocs.io/en/latest/flow_setup.html#installing-flow-and-sumo and https://flow.readthedocs.io/en/latest/flow_setup.html#optional-install-ray-rllib, I wanted to run the rllib tutorial https://github.com/flow-project/flow/blob/master/tutorials/tutorial03_rllib.ipynb .

Leave empty if not applicable.
1. File in which error occurred. 

2. Exact command that was run that caused the error to occur. 
3. Please attach the full error output log. 
[tutorial03_rllib.zip](https://github.com/flow-project/flow/files/2825567/tutorial03_rllib.zip)

**Expected behavior**
The tutorial should run through without errors when following the installation instructions.

**Screenshots**
Leave empty if not applicable.

**Desktop (please complete the following information):**
 - OS: kubuntu 18.04 with anaconda
 - Commit number of flow: 1067b8c690c42d4326bb960ec67e2483535b35e1
 - Version: 0.3.0 
 Leave empty if not applicable.

**Additional context**

**Comment by AboudyKreidieh** [comment]
hey @ae137 thank you for bring this up. The tutorial is out-of-date with respect to the current version of ray we are using (0.6.1). There is a new PR up to resolve this. Feel free to use it in the meantime! (see #408)

**Comment by niyathipriya** [comment]
Hello @AboudyKreidieh .. Thank you for mentioning the change. It was very useful for me as well. I have tried to run the example with the new code lines but still I couldn't run it. It is giving the similar error saying "NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',) ".  Is there something else which I have to do it apart from these changes?

**Comment by AboudyKreidieh** [comment]
the fix has been merged into master, so closing. If you have any other questions, feel free to start another issue or reopen this one

**Comment by ae137** [comment]
Thanks for fixing!
