### ISSUE TITLE
Tutorial04_rllab - AttributeError: 'Monitor' object has no attribute '_close'

### ISSUE THREAD

**Issue by KidTrunks** [flow-project/flow#418]
Versions:
Ubuntu 18.04
Tried with python 2 python 3

Problem:
The following error code occurs after running experiment:

Loading configuration... done.
Success.
WARNING: lz4 not available, disabling sample compression. This will significantly impact RLlib performance. To install lz4, run `pip install lz4`.
Loading configuration... done.
2019-02-20 09:28:26.084209 AEDT | [training_example_2019_02_20_09_28_17_0001] observation space: Box(3,)
2019-02-20 09:28:26.084536 AEDT | [training_example_2019_02_20_09_28_17_0001] action space: Box(1,)
2019-02-20 09:28:26.649622 AEDT | [training_example_2019_02_20_09_28_17_0001] Populating workers...
2019-02-20 09:28:26.649950 AEDT | [training_example_2019_02_20_09_28_17_0001] Populated
Loading configuration... done.
Success.

-----------------------
ring length: 259
v_max: 5.092292348291853
-----------------------
Loading configuration... done.
0% [###############               ] 100% | ETA: 00:00:04Loading configuration... done.
Success.

-----------------------
ring length: 236
v_max: 3.999052674951912
-----------------------
Loading configuration... done.
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:08
2019-02-20 09:28:34.909902 AEDT | [training_example_2019_02_20_09_28_17_0001] itr #0 | fitting baseline...
/home/python/rllab-multiagent/rllab/baselines/linear_feature_baseline.py:41: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  featmat.T.dot(returns)
2019-02-20 09:28:34.914264 AEDT | [training_example_2019_02_20_09_28_17_0001] itr #0 | fitted
=: Compiling function f_loss
done in 0.383 seconds
=: Compiling function constraint
done in 0.198 seconds
2019-02-20 09:28:35.502079 AEDT | [training_example_2019_02_20_09_28_17_0001] itr #0 | computing loss before
2019-02-20 09:28:35.504333 AEDT | [training_example_2019_02_20_09_28_17_0001] itr #0 | performing update
2019-02-20 09:28:35.504711 AEDT | [training_example_2019_02_20_09_28_17_0001] itr #0 | computing descent direction
=: Compiling function f_grad
done in 0.527 seconds
=: Compiling function f_Hx_plain
done in 1.429 seconds
2019-02-20 09:28:37.595557 AEDT | [training_example_2019_02_20_09_28_17_0001] itr #0 | descent direction computed
=: Compiling function f_loss_constraint
done in 0.331 seconds
2019-02-20 09:28:37.961054 AEDT | [training_example_2019_02_20_09_28_17_0001] itr #0 | Line search condition violated. Rejecting the step!
2019-02-20 09:28:37.961380 AEDT | [training_example_2019_02_20_09_28_17_0001] itr #0 | Violated because loss not improving
2019-02-20 09:28:37.961786 AEDT | [training_example_2019_02_20_09_28_17_0001] itr #0 | backtrack iters: 14
2019-02-20 09:28:37.961961 AEDT | [training_example_2019_02_20_09_28_17_0001] itr #0 | computing loss after
2019-02-20 09:28:37.962145 AEDT | [training_example_2019_02_20_09_28_17_0001] itr #0 | optimization finished
2019-02-20 09:28:37.964623 AEDT | [training_example_2019_02_20_09_28_17_0001] itr #0 | saving snapshot...
2019-02-20 09:28:37.993530 AEDT | [training_example_2019_02_20_09_28_17_0001] itr #0 | saved
2019-02-20 09:28:37.994502 AEDT | -----------------------  ---------------
2019-02-20 09:28:37.994692 AEDT | Iteration                    0
2019-02-20 09:28:37.994856 AEDT | AverageDiscountedReturn  -1921.04
2019-02-20 09:28:37.995017 AEDT | AverageReturn            -2448.32
2019-02-20 09:28:37.995174 AEDT | ExplainedVariance            3.16414e-14
2019-02-20 09:28:37.995354 AEDT | NumTrajs                     2
2019-02-20 09:28:37.995521 AEDT | Entropy                      1.41894
2019-02-20 09:28:37.995679 AEDT | Perplexity                   4.13273
2019-02-20 09:28:37.995835 AEDT | StdReturn                   47.1759
2019-02-20 09:28:37.995992 AEDT | MaxReturn                -2401.14
2019-02-20 09:28:37.996149 AEDT | MinReturn                -2495.49
2019-02-20 09:28:37.996376 AEDT | AveragePolicyStd             1
2019-02-20 09:28:37.996549 AEDT | LossBefore                   2.40918e-16
2019-02-20 09:28:37.996707 AEDT | LossAfter                    2.40918e-16
2019-02-20 09:28:37.996863 AEDT | MeanKLBefore                 0
2019-02-20 09:28:37.997020 AEDT | MeanKL                       0
2019-02-20 09:28:37.997177 AEDT | dLoss                        0
2019-02-20 09:28:37.997365 AEDT | -----------------------  ---------------
Traceback (most recent call last):
  File "/home/python/rllab-multiagent/scripts/run_experiment_lite.py", line 137, in <module>
    run_experiment(sys.argv)
  File "/home/python/rllab-multiagent/scripts/run_experiment_lite.py", line 121, in run_experiment
    method_call(variant_data)
  File "Tutorial04_rllab_JN.py", line 106, in run_task
    algo.train(),
  File "/home/python/rllab-multiagent/rllab/algos/batch_polopt.py", line 179, in train
    self.shutdown_worker()
  File "/home/python/rllab-multiagent/rllab/algos/batch_polopt.py", line 136, in shutdown_worker
    self.sampler.shutdown_worker()
  File "/home/python/rllab-multiagent/rllab/algos/batch_polopt.py", line 24, in shutdown_worker
    parallel_sampler.terminate_task(scope=self.algo.scope)
  File "/home/python/rllab-multiagent/rllab/sampler/parallel_sampler.py", line 68, in terminate_task
    [(scope,)] * singleton_pool.n_parallel
  File "/home/python/rllab-multiagent/rllab/sampler/stateful_pool.py", line 87, in run_each
    return [runner(self.G, *args_list[0])]
  File "/home/python/rllab-multiagent/rllab/sampler/parallel_sampler.py", line 43, in _worker_terminate_task
    G.env.terminate()
  File "/home/python/rllab-multiagent/rllab/envs/proxy_env.py", line 39, in terminate
    self._wrapped_env.terminate()
  File "/home/python/rllab-multiagent/rllab/envs/gym_env.py", line 128, in terminate
    self.env._close()
AttributeError: 'Monitor' object has no attribute '_close'
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).

Any help would be appreciated. Thanks.

**Comment by AboudyKreidieh** [comment]
hi @KidTrunks I believe your experiment did successfully run to completion. The error instead seems to be coming from the RL library rllab when it tries to terminate the environment after everything is complete. I will look into this and see if I can get rid of the bug, but rest assured your experiment was fine!

**Comment by KidTrunks** [comment]
Ahh I see. Thank you for the clarification.

You may close it now!

**Comment by KidTrunks** [comment]
Hi @AboudyKreidieh ,

Sorry for coming back to the same issue again, but I don't think the simulation run to it's completion.

After playing with # of rollouts and times steps the simulation on the SUMO gui always terminates at 50 seconds. I have attached a screenshot for you to see and the error code is the same as previous. 

I apologise in advance if everything was fine like you said, but it is vital I get this to run properly for my research. 

Regards.


![AV](https://user-images.githubusercontent.com/45654203/54414650-f2055380-474d-11e9-8524-a53adb8787fe.png)
