### ISSUE TITLE
Traffic light control with RL

### ISSUE THREAD

**Issue by lucfisc** [flow-project/flow#434]
@AboudyKreidieh 

In the branch Meng-Master ( for minicity). We tried to add Traffic light by using
(tl_logic.add("n_i4", tls_type="actuated", programID=1)) to rllib/minicity.py/flow_params (via a tl_logic dict), the traffic light n_i4 wasn’t being recognized and we would get a ‘traffic light not found’ error. 

The solution was to change that node’s type to ‘traffic_light’ in in scenarios/minicity.py/specify_nodes() but I don t know how I could do it with the first method.

Thanks

**Comment by AboudyKreidieh** [comment]
hi @lucfisc from the way the runner script is written, I think u need to add this starting from line 116:

```
        elif node_id == 'n_i4':
            tl_logic.add(node_id, phases=phases_3,
                         tls_type="actuated", programID=1)
```

tested it locally and it works. hope this helps!

**Comment by umangs94** [comment]
Hey, I tried this but I am still seeing errors. I committed my code to _meng_tl_issue_.

`Traceback (most recent call last):
  File "/Users/umang/ray/python/ray/worker.py", line 856, in _process_task
    *arguments)
  File "/Users/umang/ray/python/ray/function_manager.py", line 481, in actor_method_executor
    method_returns = method(actor, *args)
  File "/Users/umang/ray/python/ray/rllib/evaluation/policy_evaluator.py", line 338, in sample
    batches = [self.sampler.get_data()]
  File "/Users/umang/ray/python/ray/rllib/evaluation/sampler.py", line 66, in get_data
    item = next(self.rollout_provider)
  File "/Users/umang/ray/python/ray/rllib/evaluation/sampler.py", line 284, in _env_runner
    async_vector_env.send_actions(actions_to_send)
  File "/Users/umang/ray/python/ray/rllib/env/async_vector_env.py", line 243, in send_actions
    self.vector_env.vector_step(action_vector)
  File "/Users/umang/ray/python/ray/rllib/env/vector_env.py", line 84, in vector_step
    obs, rew, done, info = self.envs[i].step(actions[i])
  File "/anaconda3/lib/python3.6/site-packages/gym/core.py", line 313, in step
    observation, reward, done, info = self.env.step(action)
  File "/anaconda3/lib/python3.6/site-packages/gym/wrappers/time_limit.py", line 31, in step
    observation, reward, done, info = self.env.step(action)
  File "/Users/umang/flow/flow/envs/base_env.py", line 468, in step
    self.apply_rl_actions(rl_actions)
  File "/Users/umang/flow/flow/envs/base_env.py", line 716, in apply_rl_actions
    self._apply_rl_actions(rl_actions)
  File "/Users/umang/flow/flow/envs/minicity_env.py", line 159, in _apply_rl_actions
    env=self)
  File "/Users/umang/flow/flow/core/traffic_lights.py", line 175, in set_state
    tlsID=node_id, state=state)
  File "/Users/umang/sumo/tools/traci/_trafficlight.py", line 203, in setRedYellowGreenState
    tc.CMD_SET_TL_VARIABLE, tc.TL_RED_YELLOW_GREEN_STATE, tlsID, state)
  File "/Users/umang/sumo/tools/traci/connection.py", line 152, in _sendStringCmd
    self._sendExact()
  File "/Users/umang/sumo/tools/traci/connection.py", line 105, in _sendExact
    raise TraCIException(prefix[1], _RESULTS[prefix[2]], err)
traci.exceptions.TraCIException: Traffic light 'n_i4' is not known`

It's the same issue that we were seeing before :(
