### ISSUE TITLE
Error Connecting to sumo via TraCI

### ISSUE THREAD

**Issue by mynkpl1998** [flow-project/flow#484]
**Choose an option**
This is a: 
- [ ] Question
- [ ] Feature request
- [x] Bug report

**Describe the issue**
I am trying to run the tutorial named as "Running Sumo Simulations". However, I am getting the traci connection error. The internal Sumo Error is given below.
```
Error: tcpip::Storage::readIsSafe: want to read 8 bytes from Storage, but only 4 remaining
Quitting (on error).
```

**To Reproduce**
Full Error Stack
```

Error during start: Traceback (most recent call last):
  File "/home/mayank/Documents/flow/flow/core/kernel/simulation/traci.py", line 154, in start_simulation
    traci_connection.setOrder(0)
  File "/home/mayank/mconda3/envs/flow/lib/python3.5/site-packages/traci/connection.py", line 300, in setOrder
    self._sendExact()
  File "/home/mayank/mconda3/envs/flow/lib/python3.5/site-packages/traci/connection.py", line 97, in _sendExact
    raise FatalTraCIError("connection closed by SUMO")
traci.exceptions.FatalTraCIError: connection closed by SUMO
```

**Desktop (please complete the following information):**
 - OS: LUbuntu 16.04 LTS
 - Version :  0.3.0
 
**Additional context**
Here is the my system ~/.bashrc file

```
# added by Miniconda3 installer
export PATH="/home/mayank/miniconda3/bin:$PATH"
export PATH="$PATH:$HOME/sumo_binaries/bin"
export SUMO_HOME="$HOME/sumo_binaries/bin"
```

Traci Import path.

`['/home/mayank/mconda3/envs/flow/lib/python3.5/site-packages/traci']
`

**Comment by AboudyKreidieh** [comment]
hi @mynkpl1998 this is an error that i've experienced before but still can't pinpoint. One solution I've had for this in the past is to uninstall sumo (i.e. delete the sumo_binaries folder) and reinstall it (run `scripts/setup_sumo_ubuntu1604.sh`) after you have run `source activate flow`. The environment might be causing some issues when trying to find some packages

**Comment by tbinetruy** [comment]
I've just upgraded my Ubuntu to 19.04 from 18.04 LTS and get the same error. Ubuntu 18.04 has Sumo 0.32 in its repo whereas 19.04 has 1.1.0. On the sumo repo, I found the following issue: https://github.com/eclipse/sumo/issues/4617, and since Flow mention to `git checkout 1d4338ab80` the sumo repo, if Sumo was installed or updated from Ubuntu recently or that sumo was compiled before checking out, I guess the error occurs. They must have done some breaking changes on the interface.

Doing a `git checkout master` on the sumo repo to bring the traci python module up to date unsurprisingly breaks Flow's traci kernel

```
File "~/mdi345/flow/flow/core/kernel/vehicle/traci.py", line 98, in update
    vehicle_obs = self.kernel_api.vehicle.getSubscriptionResults()
TypeError: getSubscriptionResults() missing 1 required positional argument: 'objectID'
```

I'm going to see how downgrading Sumo from the Ubuntu repo works out as I'd like to avoid having to compile Sumo 0.32 and its dependencies by hand. I'll edit this message when I have some good news ;)

*P.S.* I note that the issue template doesn't include a field for Sumo/Aimsun, I think it'd be a good idea to add one since all of Flow's kernels involves these dependencies ;)


Cheers
