### ISSUE TITLE
FLOW adding new algorithm through Rllib 

### ISSUE THREAD

**Issue by pnp91** [flow-project/flow#501]
**Choose an option**
This is a: 
- [x] Question
- [x] Bug report

**Describe the issue**
I have added new algorithm named SAC inside agents folder of Rllib to access it as a predefined algorithms like ddpg,ppo e.t.c. But when I add it, I am getting the following errors. Is there any possible way which  I can get out of it? I have also added it inside the 'flow' env created in anaconda environments. Also, there is a 'registry.py' file inside (Path : anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents) this flow environment created in anaconda and I have added sac function call there as well. But still, I face these errors and cannot train my model using SAC algorithm.

**To Reproduce**
(flow) niyathipriya@linuxpriya:~/flow$ python MyExperiments/velocity_bottleneck_SAC.py 
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-04-15_16-45-14_31179/logs.
Waiting for redis server at 127.0.0.1:59023 to respond...
Waiting for redis server at 127.0.0.1:61535 to respond...
Starting the Plasma object store with 13.46236416 GB memory using /dev/shm.
I0415 16:45:14.845731 31194 store.cc:994] Allowing the Plasma store to use up to 13.4624GB of memory.
I0415 16:45:14.845952 31194 store.cc:1024] Starting object store with directory /dev/shm and huge page support disabled

======================================================================
View the web UI at http://localhost:8901/notebooks/ray_ui.ipynb?token=e3679a5ea7f1d5899a54eac0bd0070064fe2e29539637c0c
======================================================================

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/5 CPUs, 0/1 GPUs
Memory usage on this node: 6.0/33.7 GB

Created LogSyncer for /home/niyathipriya/ray_results/DesiredVelocity_SAC/SAC_DesiredVelocityEnv-v0_0_2019-04-15_16-45-157l5ep0gr -> 
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 5/5 CPUs, 0/1 GPUs
Memory usage on this node: 6.1/33.7 GB
Result logdir: /home/niyathipriya/ray_results/DesiredVelocity_SAC
RUNNING trials:
 - SAC_DesiredVelocityEnv-v0_0:	RUNNING

Error processing event.
Traceback (most recent call last):
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 261, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 211, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 2386, in get
    raise value
ray.worker.RayTaskError: ray_SACAgent:train() (pid=31200, host=linuxpriya)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/agent.py", line 244, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/trainable.py", line 87, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/agent.py", line 304, in _setup
    self._allow_unknown_subkeys)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/utils/__init__.py", line 35, in deep_update
    raise Exception("Unknown config parameter `{}` ".format(k))
Exception: Unknown config parameter `lambda` 

Worker ip unknown, skipping log sync for /home/niyathipriya/ray_results/DesiredVelocity_SAC/SAC_DesiredVelocityEnv-v0_0_2019-04-15_16-45-157l5ep0gr
Attempting to recover trial state from last checkpoint.
I0415 16:45:20.499881 31194 store.cc:599] Disconnecting client on fd 11
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 5/5 CPUs, 0/1 GPUs
Memory usage on this node: 6.3/33.7 GB
Result logdir: /home/niyathipriya/ray_results/DesiredVelocity_SAC
RUNNING trials:
 - SAC_DesiredVelocityEnv-v0_0:	RUNNING, 1 failures: /home/niyathipriya/ray_results/DesiredVelocity_SAC/SAC_DesiredVelocityEnv-v0_0_2019-04-15_16-45-157l5ep0gr/error_2019-04-15_16-45-20.txt

**Screenshots**
Same error attached with screenshot for ease of understanding
![Screenshot from 2019-04-16 08-40-16](https://user-images.githubusercontent.com/33332697/56187620-73892380-6023-11e9-886a-782c3cca7145.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version of Flow: 0.3.0
 - Version of Ray: 0.6.1
 - Version of Python: 3.5.2

**Comment by AboudyKreidieh** [comment]
hi @pnp91 it looks like the issue may be a missing config variable, namely:

```
 Exception: Unknown config parameter lambda
```

Can you look into whether you are not providing this input to the config file? If so, we can discuss this again from there.

**Comment by pnp91** [comment]
Hey @AboudyKreidieh, thank you so much for your reply. Sorry I had to get back to you late due to my experiments. I have tried introducing new parameter lamba as you have suggested. It works now partially with few examples of Flow except for figure_eight.py. It starts failing after a certain time running only min of 7 successful training iterations. Vehicles keep teleporting due to increased number of collisions. And because of this, there is increased time in departure, even though I have not set it manually. 

Warning: Teleporting vehicle 'human_8'; collision with vehicle 'human_9', lane='lower_ring_0', gap=-0.09, time=2023.90 stage=move.
Warning: Vehicle 'human_8' ends teleporting on edge 'bottom', time 2023.90.
Warning: Teleporting vehicle 'human_9'; collision with vehicle 'human_10', lane='lower_ring_0', gap=-0.05, time=2041.50 stage=move.
Warning: Vehicle 'human_9' ends teleporting on edge 'bottom', time 2041.50.
Warning: Teleporting vehicle 'human_9'; collision with vehicle 'human_10', lane='lower_ring_0', gap=-0.12, time=2059.60 stage=move.
Warning: Vehicle 'human_9' ends teleporting on edge 'bottom', time 2059.60.
Error: Answered with error to command 0xc4: Departure time in the past.
Error: Answered with error to command 0xc4: Vehicle 'human_0' is not known
Error processing event.
Traceback (most recent call last):
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 261, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 211, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 2386, in get
    raise value
ray.worker.RayTaskError: ray_SACAgent:train() (pid=12676, host=linuxpriya)
  File "/home/niyathipriya/flow/flow/envs/base_env.py", line 450, in reset
    speed=speed)
  File "/home/niyathipriya/flow/flow/core/kernel/vehicle/traci.py", line 920, in add
    departSpeed=str(speed))
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/traci/_vehicle.py", line 1223, in addFull
    self._connection._sendExact()
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/traci/connection.py", line 104, in _sendExact
    raise TraCIException(prefix[1], _RESULTS[prefix[2]], err)
traci.exceptions.TraCIException: Departure time in the past.

During handling of the above exception, another exception occurred:

ray_SACAgent:train() (pid=12676, host=linuxpriya)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/agent.py", line 279, in train
    result = Trainable.train(self)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/trainable.py", line 146, in train
    result = self._train()
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/sac/sac.py", line 246, in _train
    obs0 = self.env.reset()
  File "/home/niyathipriya/flow/flow/envs/loop/loop_accel.py", line 167, in reset
    obs = super().reset()
  File "/home/niyathipriya/flow/flow/envs/base_env.py", line 456, in reset
    self.k.kernel_api.vehicle.remove(veh_id)  # FIXME: hack
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/traci/_vehicle.py", line 1229, in remove
    tc.CMD_SET_VEHICLE_VARIABLE, tc.REMOVE, vehID, reason)
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/traci/connection.py", line 141, in _sendByteCmd
    self._sendExact()
  File "/home/niyathipriya/anaconda3/envs/flow/lib/python3.5/site-packages/traci/connection.py", line 104, in _sendExact
    raise TraCIException(prefix[1], _RESULTS[prefix[2]], err)
traci.exceptions.TraCIException: Vehicle 'human_0' is not known

**Comment by eugenevinitsky** [comment]
Hi @pnp91 did you install SUMO via our binary? This is a bug in an old version of SUMO that we have patched in the binary. Basically, once a certain number of time-steps is taken, SUMO bugs out.

**Comment by pnp91** [comment]
@eugenevinitsky  Thank you for your reply. Yes. I have installed through the set up given through this link https://berkeleyflow.readthedocs.io/en/latest/flow_setup.html#sumo
But problem still persists. I am using Ubuntu 18.04. Could it be a problem with version?

**Comment by AboudyKreidieh** [comment]
hi @pnp91 older versions of sumo have this bug. You can see how to fix it here: https://github.com/flow-project/flow/blob/master/docs/sumo-depart-time-issue.md

Note that this is a bit outdated, but you should be able to find the same line, and replacing it with the recommended line should fix the problem. Hope this helps! Let me know if it doesn't work.

**Comment by pnp91** [comment]
Hi @AboudyKreidieh Thank you so much for this advise and it really helped a lot after I changed it:)
