### ISSUE TITLE
Visualization - Plotting Reward

### ISSUE THREAD

**Issue by KidTrunks** [flow-project/flow#543]
![Internal Server error](https://user-images.githubusercontent.com/45654203/59170054-29827100-8b80-11e9-96e6-7654fd7cca42.png)
**This is a:**
Question

**Describe the Issue:**
Hi I am trying to visualize Automated vehicle learning by using the plotting reward function. The simulation has run to it's completion and I made sure the progress.csv and .json files are in the folder. The .json file was variant.json instead of params.json. 

However after clicking _View http://localhost:5000 in your browser,_ 
I encountered 500 internal server error and the following error code:

(flow) python@python-VirtualBox:~/rllab-multiagent/rllab/viskit$ python frontend.py /home/python/rllab-multiagent/data/local/stabilizing-the-ring/stabilizing-the-ring_2019_05_19/
Importing data from ['/home/python/rllab-multiagent/data/local/stabilizing-the-ring/stabilizing-the-ring_2019_05_19/']...
Reading /home/python/rllab-multiagent/data/local/stabilizing-the-ring/stabilizing-the-ring_2019_05_19/progress.csv
Reading /home/python/rllab-multiagent/data/local/stabilizing-the-ring/stabilizing-the-ring_2019_05_19/gym_log/progress.csv
Done! View http://localhost:5000 in your browser
 * Serving Flask app "frontend" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
AverageReturn None None None
[]
[]
[]
[2019-06-10 12:42:48,202] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "frontend.py", line 534, in index
    plot_key=plot_key, split_key=None, group_key=group_key)
  File "frontend.py", line 437, in get_plot_instruction
    plot_width=plot_width, plot_height=plot_height
  File "frontend.py", line 114, in make_plot
    title=title,
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/plotly/graph_objs/graph_objs.py", line 375, in __init__
    self.__setitem__(key, val, _raise=_raise)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/plotly/graph_objs/graph_objs.py", line 430, in __setitem__
    value = self._value_to_graph_object(key, value, _raise=_raise)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/plotly/graph_objs/graph_objs.py", line 535, in _value_to_graph_object
    raise exceptions.PlotlyDictValueError(self, path)
plotly.exceptions.PlotlyDictValueError: 'title' has invalid value inside 'layout'

Path To Error: ['title']

Current path: []
Current parent object_names: []

With the current parents, 'title' can be used as follows:

Under ('figure', 'layout'):

    editType: layoutstyle
    role: object

127.0.0.1 - - [10/Jun/2019 12:42:48] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [10/Jun/2019 12:42:48] "GET /favicon.ico HTTP/1.1" 404 -

**OS:** Ubuntu 18.04

Thanks, any help would be appreciated.

**Comment by AboudyKreidieh** [comment]
hi @KidTrunks we're looking into this now and will get back to you soon!

**Comment by KidTrunks** [comment]
Cheers @AboudyKreidieh let me know if you need any other information. 

Regards.

**Comment by kjang96** [comment]
Hi @KidTrunks, apologies for getting to you late on this. Our team is mostly moving to RLlib now, so we've been slower on rllab issues. I managed to recreate your error. This is likely a versioning issue. Can you try using Flask 0.12.2 and tell me if the problem still persists?

**Comment by kjang96** [comment]
Update -- it looks like the problem should be fixed without changing Flask. The versioning issue is with plotly. Try running `conda install plotly=2.4.0` in your env.

**Comment by KidTrunks** [comment]
Thanks @kjang96 worked like a charm!
