### ISSUE TITLE
running rllib/greenwave.py

### ISSUE THREAD

**Issue by basit2120** [flow-project/flow#556]
This is a: **Question**

**Describe the issue**
when ever i try to rub green wave file present in rllib i come across this issue

**To Reproduce**

```
(flow) basit@basit:~/flow$ python examples/rllib/green_wave.py 
/home/basit/flow/flow/utils/flow_warnings.py:20: UserWarning: The attribute minGap in SumoCarFollowingParams is deprecated, use min_gap instead.
  dep_from, obj.__class__.__name__, dep_to))
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-06-19_11-15-25_29934/logs.
Waiting for redis server at 127.0.0.1:14802 to respond...
Waiting for redis server at 127.0.0.1:58187 to respond...
Starting the Plasma object store with 3.220642201 GB memory using /dev/shm.
I0619 11:15:26.333153 29950 store.cc:994] Allowing the Plasma store to use up to 3.22064GB of memory.
I0619 11:15:26.333390 29950 store.cc:1024] Starting object store with directory /dev/shm and huge page support disabled
Failed to start the UI, you may need to run 'pip install jupyter'.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/3 CPUs, 0/0 GPUs
Memory usage on this node: 2.0/8.1 GB

Created LogSyncer for /home/basit/ray_results/green_wave/PPO_PO_TrafficLightGridEnv-v0_0_2019-06-19_11-15-2639_rv7y9 -> 
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 3/3 CPUs, 0/0 GPUs
Memory usage on this node: 2.0/8.1 GB
Result logdir: /home/basit/ray_results/green_wave
RUNNING trials:
 - PPO_PO_TrafficLightGridEnv-v0_0:	RUNNING

2019-06-19 11:15:32,842	WARNING ppo.py:137 -- By default, observations will be normalized with MeanStdFilter
Loading configuration... done.
Success.
 Starting SUMO on port 50949
Loading configuration... done.
2019-06-19 11:15:33,968	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
2019-06-19 11:15:33.969000: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2019-06-19 11:15:35,085	INFO multi_gpu_optimizer.py:74 -- LocalMultiGPUOptimizer devices ['/cpu:0']
Loading configuration... done.
Success.
 Starting SUMO on port 55511
Loading configuration... done.
2019-06-19 11:15:43,028	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 1 on CPU (please ignore any CUDA init errors)
2019-06-19 11:15:43.029533: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Loading configuration... done.
Success.
 Starting SUMO on port 32911
Loading configuration... done.
2019-06-19 11:15:44,860	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 2 on CPU (please ignore any CUDA init errors)
2019-06-19 11:15:44.861973: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Warning: Vehicle 'idm_8' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=17.00.
Warning: Vehicle 'idm_6' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=17.00.
Warning: Vehicle 'idm_8' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=18.00.
Warning: Vehicle 'idm_4' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=38.00.
Warning: Vehicle 'idm_8' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=42.00.
Warning: Vehicle 'idm_2' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=49.00.
Warning: Vehicle 'idm_9' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=51.00.
Warning: Vehicle 'idm_10' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=57.00.
Warning: Vehicle 'idm_10' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=217.00.
Warning: Vehicle 'idm_10' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=232.00.
Warning: Vehicle 'idm_2' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=239.00.
Warning: Vehicle 'idm_3' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=237.00.
Warning: Vehicle 'idm_3' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=254.00.
Warning: Vehicle 'idm_3' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=260.00.
Warning: Vehicle 'idm_10' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=419.00.
Warning: Vehicle 'idm_6' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=419.00.
Warning: Vehicle 'idm_5' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=420.00.
Warning: Vehicle 'idm_8' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=431.00.
Warning: Vehicle 'idm_1' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=432.00.
Warning: Vehicle 'idm_4' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=436.00.
Warning: Vehicle 'idm_1' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=455.00.
Warning: Vehicle 'idm_1' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=456.00.
Warning: Vehicle 'idm_3' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=621.00.
Warning: Vehicle 'idm_6' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=621.00.
Warning: Vehicle 'idm_9' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=643.00.
Warning: Vehicle 'idm_9' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=660.00.
Warning: Vehicle 'idm_10' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=821.00.
Warning: Vehicle 'idm_1' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=822.00.
Warning: Vehicle 'idm_0' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=821.00.
Warning: Vehicle 'idm_3' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=822.00.
Warning: Vehicle 'idm_3' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=831.00.
Warning: Vehicle 'idm_5' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=837.00.
Warning: Vehicle 'idm_6' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=832.00.
Warning: Vehicle 'idm_5' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=840.00.
Warning: Vehicle 'idm_8' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=856.00.
Warning: Vehicle 'idm_3' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=854.00.
Warning: Vehicle 'idm_0' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=858.00.
Warning: Vehicle 'idm_2' performs emergency braking with decel=-9.00 wished=7.50 severity=1.00, time=864.00.
Error: Answered with error to command 0xc4: Invalid departLane definition for vehicle 'idm_0';
 must be one of ("random", "free", "allowed", "best", "first", or an int>=0)
Error: Answered with error to command 0xc4: Vehicle 'idm_0' is not known
Error processing event.
Traceback (most recent call last):
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 261, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 211, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 2386, in get
    raise value
ray.worker.RayTaskError: ray_PPOAgent:train() (pid=29958, host=basit)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/agent.py", line 279, in train
    result = Trainable.train(self)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/trainable.py", line 146, in train
    result = self._train()
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/ppo/ppo.py", line 101, in _train
    fetches = self.optimizer.step()
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 125, in step
    self.num_envs_per_worker, self.train_batch_size)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/optimizers/rollout.py", line 28, in collect_samples
    next_sample = ray.get(fut_sample)
ray.worker.RayTaskError: ray_PolicyEvaluator:sample() (pid=29969, host=basit)
  File "/home/basit/flow/flow/envs/base_env.py", line 483, in reset
    speed=speed)
  File "/home/basit/flow/flow/core/kernel/vehicle/traci.py", line 994, in add
    departSpeed=str(speed))
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/traci/_vehicle.py", line 1427, in add
    self._connection._sendExact()
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/traci/connection.py", line 106, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Invalid departLane definition for vehicle 'idm_0';
 must be one of ("random", "free", "allowed", "best", "first", or an int>=0)

During handling of the above exception, another exception occurred:

ray_PolicyEvaluator:sample() (pid=29969, host=basit)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 368, in sample
    batches = [self.input_reader.next()]
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/offline/input_reader.py", line 25, in next
    batches = [self.sampler.get_data()]
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 64, in get_data
    item = next(self.rollout_provider)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 267, in _env_runner
    preprocessors, obs_filters, unroll_length, pack, callbacks)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 406, in _process_observations
    resetted_obs = async_vector_env.try_reset(env_id)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/env/async_vector_env.py", line 252, in try_reset
    return {_DUMMY_AGENT_ID: self.vector_env.reset_at(env_id)}
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/env/vector_env.py", line 83, in reset_at
    return self.envs[index].reset()
  File "/home/basit/flow/flow/envs/base_env.py", line 489, in reset
    self.k.kernel_api.vehicle.remove(veh_id)  # FIXME: hack
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/traci/_vehicle.py", line 1435, in remove
    tc.CMD_SET_VEHICLE_VARIABLE, tc.REMOVE, vehID, reason)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/traci/connection.py", line 143, in _sendByteCmd
    self._sendExact()
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/traci/connection.py", line 106, in _sendExact
    raise TraCIException(err, prefix[1], _RESULTS[prefix[2]])
traci.exceptions.TraCIException: Vehicle 'idm_0' is not known
```

**Desktop (please complete the following information):**
 - OS: ubuntu 18.06

**Comment by nathanlct** [comment]
Hello @basit2120,

Are you still having this issue? If yes, could you please ask your question on [StackOverflow](overflow.com/questions/tagged/flow-project) using the tag `flow-project`? You should get an answer quickly on there.

Thank you!

**Comment by basit2120** [comment]
no i have fixed the error.

**Comment by guilhermevarela** [comment]
> no i have fixed the error.

@basit2120 I'm just experiencing that exception, How did you fixed it?

**Comment by basit2120** [comment]
first i install Jupyter in flow environment and secondly use the old version of flow. In latest version i'm still  facing this issue.

**Comment by KidTrunks** [comment]
Hi @basit2120 I am having the same problem. Could you please let me know which old version of FLOW solved this issue? And how did you install the old version?

**Comment by Tabbi7** [comment]
I have the same problem. How can I fix the error?

**Comment by basit2120** [comment]
I had no idea now because I have all lost all of my data due to hard dick
issue
That's why I can't help you is this
Sorry.

**Comment by roireshef** [comment]
> I had no idea now because I have all lost all of my data due to hard dick issue

Definitely a weird issue. I wonder how you managed to solve that issue...

**Comment by roireshef** [comment]
> I had no idea now because I have all lost all of my data due to hard dick issue

Definitely a weird issue. I wonder how you managed to solve that issue... :))
