### ISSUE TITLE
DeprecationWarning: The redirect_output arguement is deprecated

### ISSUE THREAD

**Issue by KidTrunks** [flow-project/flow#559]
**This is a:**
Question

**OS**: Ubuntu 18.04

**Describe the Issue:**
Hi, I am trying to run Tutorial03_rllib. Only minor adjustments to the Tutorial code is made and the following error was encountered:

Traceback (most recent call last):
  File "stabilizing_the_ring.py", line 123, in <module>
    ray.init(num_cpus=N_CPUS, redirect_output=True)
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 1442, in init
    _internal_config=_internal_config,
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/parameter.py", line 148, in __init__
    self._check_usage()
  File "/home/python/anaconda3/envs/flow/lib/python3.5/site-packages/ray/parameter.py", line 198, in _check_usage
    "The redirect_output argument is deprecated.")
DeprecationWarning: The redirect_output argument is deprecated.

I have attached my code if you would like to have a look. Any help would be appreciated.

Thanks.

[stabilizing_the_ring_rllib.txt](https://github.com/flow-project/flow/files/3316475/stabilizing_the_ring_rllib.txt)

**Comment by KidTrunks** [comment]
Hi it worked after deleting  (redirect_output=True)

You may close the issue. Thanks.
