### ISSUE TITLE
how to print variables

### ISSUE THREAD

**Issue by basit2120** [flow-project/flow#579]
This is a: **Question**

when ever i try to print anything from green wave environment i get following error

```
/home/basit/flow/flow/utils/flow_warnings.py:20: UserWarning: The attribute minGap in SumoCarFollowingParams is deprecated, use min_gap instead.
  dep_from, obj.__class__.__name__, dep_to))
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-07-01_15-07-16_3441/logs.
Waiting for redis server at 127.0.0.1:36628 to respond...
Waiting for redis server at 127.0.0.1:21131 to respond...
Starting the Plasma object store with 3.220642201 GB memory using /dev/shm.
I0701 15:07:16.850232  3470 store.cc:994] Allowing the Plasma store to use up to 3.22064GB of memory.
I0701 15:07:16.850700  3470 store.cc:1024] Starting object store with directory /dev/shm and huge page support disabled

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui.ipynb?token=a746556feecf676c6e4a4da121e33d9428fead90bde544d0
======================================================================

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/5 CPUs, 0/0 GPUs
Memory usage on this node: 2.5/8.1 GB

Created LogSyncer for /home/basit/ray_results/green_wave/PPO_PO_TrafficLightGridEnv-v0_0_2019-07-01_15-07-17rm_e_l1z -> 
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 5/5 CPUs, 0/0 GPUs
Memory usage on this node: 2.5/8.1 GB
Result logdir: /home/basit/ray_results/green_wave
RUNNING trials:
 - PPO_PO_TrafficLightGridEnv-v0_0:	RUNNING

Loading configuration... done.
Success.
 Starting SUMO on port 36297
Loading configuration... done.
2019-07-01 15:07:27,580	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
2019-07-01 15:07:27.582169: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Error processing event.
Traceback (most recent call last):
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 261, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 211, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 2386, in get
    raise value
ray.worker.RayTaskError: ray_PPOAgent:train() (pid=3479, host=basit)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/agent.py", line 244, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/trainable.py", line 87, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/agent.py", line 312, in _setup
    self._init()
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/ppo/ppo.py", line 77, in _init
    self.env_creator, self._policy_graph)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/agent.py", line 413, in make_local_evaluator
    config["local_evaluator_tf_session_args"]
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/agent.py", line 533, in _make_evaluator
    output_creator=output_creator)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 272, in __init__
    self._build_policy_map(policy_dict, policy_config)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 567, in _build_policy_map
    obs_space, merged_conf.get("model"))
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/models/catalog.py", line 303, in get_preprocessor_for_space
    cls = get_preprocessor(observation_space)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/models/preprocessors.py", line 198, in get_preprocessor
    legacy_patch_shapes(space)
  File "/home/basit/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/models/preprocessors.py", line 233, in legacy_patch_shapes
    return space.shape
AttributeError: 'NoneType' object has no attribute 'shape'
```

**Comment by nathanlct** [comment]
Hello @basit2120,

Do you not get the error when you don't print? 
Can you provide us with the command that you ran and potentially the code that you modified and that is concerned by the issue? 

Thank you!

**Comment by basit2120** [comment]
Hi Nathan Lichtlé
No i don't get the error when i execute the code without print function
the command is
python flow/examples/rllib/green_wave.py

**Comment by basit2120** [comment]
No i don't get the error when i execute the code without print function 
the command is 
python flow/examples/rllib/green_wave.py

**Comment by nathanlct** [comment]
So you deleted your comment, have you fixed the issue or not? 

If not, can you copy/paste the part of the code where you have the print function?

Thanks!

**Comment by basit2120** [comment]
yes i have fixed the issue.
