### ISSUE TITLE
ray_autoscale not working

### ISSUE THREAD

**Issue by kjang96** [flow-project/flow#598]
## Bug Description

Running RLlib experiments on EC2 is currently broken. First, pyarrow isn't installed on the AMI (the default is ami-0067051ba5c8f0b64). Second, I tried with an AMI that does have pyarrow (made ami-09ee73f99ee3510b0 for this purpose, title 'kathy'), and the setup commands don't work.

## Bug Reproduce

scripts/ray_autoscale.yaml

The exact command that you did run that caused the bug:
`command`
`ray up ray_autoscale.yaml -y`

## Output Log

Full error output log:

```
NodeUpdater: running 

	ray stop

 on 54.153.94.112...
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/ray", line 7, in <module>
    from ray.scripts.scripts import main
  File "/home/ubuntu/ray/python/ray/__init__.py", line 28, in <module>
    import pyarrow  # noqa: F401
ModuleNotFoundError: No module named 'pyarrow'
NodeUpdater: Error updating (Exit Status 1) 

	ssh -o ConnectTimeout=120s -o StrictHostKeyChecking=no -i /Users/kathyjang/.ssh/ray-autoscaler_3_us-west-1.pem ubuntu@54.153.94.112 bash --login -c 'set -i || true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && ray stop'

See (console) for remote logs.
Process NodeUpdaterProcess-1:
Traceback (most recent call last):
  File "/Users/kathyjang/anaconda/envs/flow/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Users/kathyjang/anaconda/envs/flow/lib/python3.5/site-packages/ray/autoscaler/updater.py", line 104, in run
    raise e
  File "/Users/kathyjang/anaconda/envs/flow/lib/python3.5/site-packages/ray/autoscaler/updater.py", line 89, in run
    self.do_update()
  File "/Users/kathyjang/anaconda/envs/flow/lib/python3.5/site-packages/ray/autoscaler/updater.py", line 176, in do_update
    self.ssh_cmd(cmd, verbose=True)
  File "/Users/kathyjang/anaconda/envs/flow/lib/python3.5/site-packages/ray/autoscaler/updater.py", line 244, in ssh_cmd
    stderr=redirect or self.stderr)
  File "/Users/kathyjang/anaconda/envs/flow/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', '-o', 'ConnectTimeout=120s', '-o', 'StrictHostKeyChecking=no', '-i', '/Users/kathyjang/.ssh/ray-autoscaler_3_us-west-1.pem', 'ubuntu@54.153.94.112', "bash --login -c 'set -i || true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && ray stop'"]' returned non-zero exit status 1
Updating 54.153.94.112 failed
```

## Screenshots

Screenshots:

![picture name](https://link/to/screenshot)

## Versions

- OS: macOS Mojave
- Flow version: 0.4.0.dev
- Flow commit number: 781d6fd239fb940a9d1e8c88d41aea49c42625a8

**Comment by cathywu** [comment]
For reference: I updated the instance and created a new AMI with SUMO 1.0.0: `ami-01c3028573a3e1b39`
