### ISSUE TITLE
Error when running multiagent examples

### ISSUE THREAD

**Issue by cathywu** [flow-project/flow#610]
## Bug Description

The multi-agent examples (rllib) error when run.

## Bug Reproduce

File in which the bug occurred: `examples/rllib/multiagent_exps/multiagent_stabilizing_the_ring.py`

The exact command that you did run that caused the bug:
`python examples/rllib/multiagent_exps/multiagent_stabilizing_the_ring.py`

There are similar errors for:
`python examples/rllib/multiagent_exps/multiagent_figure_eight.py`

## Output Log

Full error output log:

```
ubuntu@ip-172-31-30-30:~/flow2$ python examples/rllib/multiagent_exps/multiagent_stabilizing_the_ring.py
/home/ubuntu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
WARNING:tensorflow:From /home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
/home/ubuntu/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Loading configuration... done.
Success.
Loading configuration... done.
WARNING:ray.worker:WARNING: Falling back to serializing objects of type <class 'numpy.dtype'> by using pickle. This may be inefficient.
/home/ubuntu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/ubuntu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/ubuntu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/ubuntu/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
From /home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
/home/ubuntu/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Loading configuration... done.
Success.
 Starting SUMO on port 40825
Loading configuration... done.
2019-07-10 23:00:11,267	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
2019-07-10 23:00:11.268654: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
ERROR:ray.tune.trial_runner:Error processing event.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 261, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 211, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 2386, in get
    raise value
ray.worker.RayTaskError: ray_PPOAgent:train() (pid=31010, host=ip-172-31-30-30)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 244, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/trainable.py", line 87, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 312, in _setup
    self._init()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/ppo/ppo.py", line 75, in _init
    self.env_creator, self._policy_graph)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 413, in make_local_evaluator
    config["local_evaluator_tf_session_args"]
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 533, in _make_evaluator
    output_creator=output_creator)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 294, in __init__
    self.env, make_env=make_env, num_envs=num_envs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 73, in wrap_async
    make_env=make_env, existing_envs=[env], num_envs=num_envs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 283, in __init__
    self.env_states = [_MultiAgentEnvState(env) for env in self.envs]
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 283, in <listcomp>
    self.env_states = [_MultiAgentEnvState(env) for env in self.envs]
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 327, in __init__
    self.reset()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 345, in reset
    self.last_obs = self.env.reset()
  File "/home/ubuntu/flow2/flow/multiagent_envs/multiagent_env.py", line 244, in reset
    observation, _, _, _ = self.step(rl_actions=None)
  File "/home/ubuntu/flow2/flow/multiagent_envs/multiagent_env.py", line 63, in step
    self.k.vehicle.get_controlled_ids(), accel)
  File "/home/ubuntu/flow2/flow/core/kernel/vehicle/traci.py", line 881, in apply_acceleration
    self.kernel_api.vehicle.slowDown(vid, next_vel, 1e-3)
  File "/home/ubuntu/sumo/tools/traci/_vehicle.py", line 812, in slowDown
    "!BiBdBi", tc.TYPE_COMPOUND, 2, tc.TYPE_DOUBLE, speed, tc.TYPE_INTEGER, duration)
struct.error: required argument is not an integer

Error: Answered with error to command 0xc4: Slow down needs a compound object description.
Error: Answered with error to command 0xc4: Wrong position in requestMessage after dispatching command. Expected command length was 35 but 18 Bytes were read.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/ubuntu/flow2/flow/envs/base_env.py", line 658, in terminate
    self.k.close()
  File "/home/ubuntu/flow2/flow/core/kernel/kernel.py", line 108, in close
    self.simulation.close()
  File "/home/ubuntu/flow2/flow/core/kernel/simulation/traci.py", line 64, in close
    self.kernel_api.close()
  File "/home/ubuntu/sumo/tools/traci/connection.py", line 307, in close
    self._sendExact()
  File "/home/ubuntu/sumo/tools/traci/connection.py", line 104, in _sendExact
    raise TraCIException(prefix[1], _RESULTS[prefix[2]], err)
traci.exceptions.TraCIException: Slow down needs a compound object description.
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
From /home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
/home/ubuntu/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Loading configuration... done.
Success.
 Starting SUMO on port 58628
Loading configuration... done.
2019-07-10 23:00:19,081	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
2019-07-10 23:00:19.082696: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
ERROR:ray.tune.trial_runner:Error processing event.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 261, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 211, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 2386, in get
    raise value
ray.worker.RayTaskError: ray_PPOAgent:train() (pid=31008, host=ip-172-31-30-30)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 244, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/trainable.py", line 87, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 312, in _setup
    self._init()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/ppo/ppo.py", line 75, in _init
    self.env_creator, self._policy_graph)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 413, in make_local_evaluator
    config["local_evaluator_tf_session_args"]
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 533, in _make_evaluator
    output_creator=output_creator)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 294, in __init__
    self.env, make_env=make_env, num_envs=num_envs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 73, in wrap_async
    make_env=make_env, existing_envs=[env], num_envs=num_envs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 283, in __init__
    self.env_states = [_MultiAgentEnvState(env) for env in self.envs]
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 283, in <listcomp>
    self.env_states = [_MultiAgentEnvState(env) for env in self.envs]
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 327, in __init__
    self.reset()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 345, in reset
    self.last_obs = self.env.reset()
  File "/home/ubuntu/flow2/flow/multiagent_envs/multiagent_env.py", line 244, in reset
    observation, _, _, _ = self.step(rl_actions=None)
  File "/home/ubuntu/flow2/flow/multiagent_envs/multiagent_env.py", line 63, in step
    self.k.vehicle.get_controlled_ids(), accel)
  File "/home/ubuntu/flow2/flow/core/kernel/vehicle/traci.py", line 881, in apply_acceleration
    self.kernel_api.vehicle.slowDown(vid, next_vel, 1e-3)
  File "/home/ubuntu/sumo/tools/traci/_vehicle.py", line 812, in slowDown
    "!BiBdBi", tc.TYPE_COMPOUND, 2, tc.TYPE_DOUBLE, speed, tc.TYPE_INTEGER, duration)
struct.error: required argument is not an integer

Error: Answered with error to command 0xc4: Slow down needs a compound object description.
Error: Answered with error to command 0xc4: Wrong position in requestMessage after dispatching command. Expected command length was 35 but 18 Bytes were read.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/ubuntu/flow2/flow/envs/base_env.py", line 658, in terminate
    self.k.close()
  File "/home/ubuntu/flow2/flow/core/kernel/kernel.py", line 108, in close
    self.simulation.close()
  File "/home/ubuntu/flow2/flow/core/kernel/simulation/traci.py", line 64, in close
    self.kernel_api.close()
  File "/home/ubuntu/sumo/tools/traci/connection.py", line 307, in close
    self._sendExact()
  File "/home/ubuntu/sumo/tools/traci/connection.py", line 104, in _sendExact
    raise TraCIException(prefix[1], _RESULTS[prefix[2]], err)
traci.exceptions.TraCIException: Slow down needs a compound object description.
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
From /home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
/home/ubuntu/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Loading configuration... done.
Success.
 Starting SUMO on port 48534
Loading configuration... done.
2019-07-10 23:00:26,753	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
2019-07-10 23:00:26.754689: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
ERROR:ray.tune.trial_runner:Error processing event.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 261, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 211, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 2386, in get
    raise value
ray.worker.RayTaskError: ray_PPOAgent:train() (pid=31121, host=ip-172-31-30-30)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 244, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/trainable.py", line 87, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 312, in _setup
    self._init()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/ppo/ppo.py", line 75, in _init
    self.env_creator, self._policy_graph)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 413, in make_local_evaluator
    config["local_evaluator_tf_session_args"]
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 533, in _make_evaluator
    output_creator=output_creator)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 294, in __init__
    self.env, make_env=make_env, num_envs=num_envs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 73, in wrap_async
    make_env=make_env, existing_envs=[env], num_envs=num_envs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 283, in __init__
    self.env_states = [_MultiAgentEnvState(env) for env in self.envs]
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 283, in <listcomp>
    self.env_states = [_MultiAgentEnvState(env) for env in self.envs]
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 327, in __init__
    self.reset()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 345, in reset
    self.last_obs = self.env.reset()
  File "/home/ubuntu/flow2/flow/multiagent_envs/multiagent_env.py", line 244, in reset
    observation, _, _, _ = self.step(rl_actions=None)
  File "/home/ubuntu/flow2/flow/multiagent_envs/multiagent_env.py", line 63, in step
    self.k.vehicle.get_controlled_ids(), accel)
  File "/home/ubuntu/flow2/flow/core/kernel/vehicle/traci.py", line 881, in apply_acceleration
    self.kernel_api.vehicle.slowDown(vid, next_vel, 1e-3)
  File "/home/ubuntu/sumo/tools/traci/_vehicle.py", line 812, in slowDown
    "!BiBdBi", tc.TYPE_COMPOUND, 2, tc.TYPE_DOUBLE, speed, tc.TYPE_INTEGER, duration)
struct.error: required argument is not an integer

Error: Answered with error to command 0xc4: Slow down needs a compound object description.
Error: Answered with error to command 0xc4: Wrong position in requestMessage after dispatching command. Expected command length was 35 but 18 Bytes were read.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/ubuntu/flow2/flow/envs/base_env.py", line 658, in terminate
    self.k.close()
  File "/home/ubuntu/flow2/flow/core/kernel/kernel.py", line 108, in close
    self.simulation.close()
  File "/home/ubuntu/flow2/flow/core/kernel/simulation/traci.py", line 64, in close
    self.kernel_api.close()
  File "/home/ubuntu/sumo/tools/traci/connection.py", line 307, in close
    self._sendExact()
  File "/home/ubuntu/sumo/tools/traci/connection.py", line 104, in _sendExact
    raise TraCIException(prefix[1], _RESULTS[prefix[2]], err)
traci.exceptions.TraCIException: Slow down needs a compound object description.
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).
From /home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
/home/ubuntu/anaconda3/lib/python3.6/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Loading configuration... done.
Success.
 Starting SUMO on port 33375
Loading configuration... done.
2019-07-10 23:00:34,425	INFO policy_evaluator.py:262 -- Creating policy evaluation worker 0 on CPU (please ignore any CUDA init errors)
2019-07-10 23:00:34.425786: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:100: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
ERROR:ray.tune.trial_runner:Error processing event.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 261, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 211, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/worker.py", line 2386, in get
    raise value
ray.worker.RayTaskError: ray_PPOAgent:train() (pid=31009, host=ip-172-31-30-30)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 244, in __init__
    Trainable.__init__(self, config, logger_creator)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/trainable.py", line 87, in __init__
    self._setup(copy.deepcopy(self.config))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 312, in _setup
    self._init()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/ppo/ppo.py", line 75, in _init
    self.env_creator, self._policy_graph)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 413, in make_local_evaluator
    config["local_evaluator_tf_session_args"]
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/agents/agent.py", line 533, in _make_evaluator
    output_creator=output_creator)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 294, in __init__
    self.env, make_env=make_env, num_envs=num_envs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 73, in wrap_async
    make_env=make_env, existing_envs=[env], num_envs=num_envs)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 283, in __init__
    self.env_states = [_MultiAgentEnvState(env) for env in self.envs]
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 283, in <listcomp>
    self.env_states = [_MultiAgentEnvState(env) for env in self.envs]
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 327, in __init__
    self.reset()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/rllib/env/async_vector_env.py", line 345, in reset
    self.last_obs = self.env.reset()
  File "/home/ubuntu/flow2/flow/multiagent_envs/multiagent_env.py", line 244, in reset
    observation, _, _, _ = self.step(rl_actions=None)
  File "/home/ubuntu/flow2/flow/multiagent_envs/multiagent_env.py", line 63, in step
    self.k.vehicle.get_controlled_ids(), accel)
  File "/home/ubuntu/flow2/flow/core/kernel/vehicle/traci.py", line 881, in apply_acceleration
    self.kernel_api.vehicle.slowDown(vid, next_vel, 1e-3)
  File "/home/ubuntu/sumo/tools/traci/_vehicle.py", line 812, in slowDown
    "!BiBdBi", tc.TYPE_COMPOUND, 2, tc.TYPE_DOUBLE, speed, tc.TYPE_INTEGER, duration)
struct.error: required argument is not an integer

Error: Answered with error to command 0xc4: Slow down needs a compound object description.
Error: Answered with error to command 0xc4: Wrong position in requestMessage after dispatching command. Expected command length was 35 but 18 Bytes were read.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/ubuntu/flow2/flow/envs/base_env.py", line 658, in terminate
    self.k.close()
  File "/home/ubuntu/flow2/flow/core/kernel/kernel.py", line 108, in close
    self.simulation.close()
  File "/home/ubuntu/flow2/flow/core/kernel/simulation/traci.py", line 64, in close
    self.kernel_api.close()
  File "/home/ubuntu/sumo/tools/traci/connection.py", line 307, in close
    self._sendExact()
  File "/home/ubuntu/sumo/tools/traci/connection.py", line 104, in _sendExact
    raise TraCIException(prefix[1], _RESULTS[prefix[2]], err)
traci.exceptions.TraCIException: Slow down needs a compound object description.
Traceback (most recent call last):
  File "examples/rllib/multiagent_exps/multiagent_stabilizing_the_ring.py", line 180, in <module>
    'config': config,
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/ray/tune/tune.py", line 124, in run_experiments
    raise TuneError("Trials did not complete", errored_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_MultiWaveAttenuationPOEnv-v0_0_lr=1e-05])
Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
Quitting (on error).```

## Screenshots

<!-- DELETE THIS SECTION IF NOT APPLICABLE -->

<!-- If possible, add screenshots to help explain the bug -->

Screenshots:

![picture name](https://link/to/screenshot)

## Versions

<!-- DELETE THIS SECTION IF NOT APPLICABLE -->

- OS: ? (For example, RedHat, macOS Mojave, ...]
- Flow version: ? (run `python -c "import flow; print(flow.__version__)"`)
- Flow commit number: ? (run `git log` and copy the commit number)

**Comment by cathywu** [comment]
The issue was that the AMI `ami-0067051ba5c8f0b64` has an older version of SUMO (and in particular, an older version of traci), so there was an API mismatch. This can be resolved by updating SUMO.
