### ISSUE TITLE
flow 0.4.0 seems to have broken mulit-agent grid experiments

### ISSUE THREAD

**Issue by cathywu** [flow-project/flow#636]
## Bug Description

After the sumo_binaries were updated in this latest upgrade to 0.4.0, I am no longer able to run my grid multi-agent experiments. I was successfully running experiments as of 0.3.1 (`commit c0c096eaf5646cf5b44a76861834a40cbc68cf2a` in `cathywu/flow:grid_avs`). Any ideas why?

## Bug Reproduce

File in which the bug occurred: `examples/rllib/multiagent_exps/multiagent_grid_avs.py` but not exactly sure where the bug is.

The exact command that you did run that caused the bug:
```
git clone https://github.com/cathywu/flow.git flow2
cd flow2
git checkout grid_avs
python examples/rllib/multiagent_exps/multiagent_grid_avs.py --upload_dir="cathywu.flow/benchmarks/20190715" --num_rows 1 --num_cols 1 --inflow_rate 700
```

## Output Log

Full error output log:

```
$ python examples/rllib/multiagent_exps/multiagent_grid_avs.py --upload_dir="cathywu.flow/benchmarks/20190715" --num_rows 1 --num_cols 1 --inflow_rate 700
...
 Starting SUMO on port 37855
Loading configuration... done.
ERROR:ray.tune.trial_runner:Error processing event.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 261, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 211, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/ray/worker.py", line 2386, in get
    raise value
ray.worker.RayTaskError: ray_PPOAgent:train() (pid=3006, host=ip-172-31-2-113)
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/agent.py", line 279, in train
    result = Trainable.train(self)
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/ray/tune/trainable.py", line 146, in train
    result = self._train()
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/agents/ppo/ppo.py", line 101, in _train
    fetches = self.optimizer.step()
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/optimizers/sync_samples_optimizer.py", line 48, in step
    e.sample.remote() for e in self.remote_evaluators
ray.worker.RayTaskError: ray_PolicyEvaluator:sample() (pid=3017, host=ip-172-31-2-113)
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/utils/tf_run_builder.py", line 47, in get
    self.feed_dict, os.environ.get("TF_TIMELINE_DIR"))
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/utils/tf_run_builder.py", line 85, in run_timeline
    fetches = sess.run(ops, feed_dict=feed_dict)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1109, in _run
    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.

During handling of the above exception, another exception occurred:

ray_PolicyEvaluator:sample() (pid=3017, host=ip-172-31-2-113)
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/policy_evaluator.py", line 368, in sample
    batches = [self.input_reader.next()]
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/offline/input_reader.py", line 25, in next
    batches = [self.sampler.get_data()]
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 64, in get_data
    item = next(self.rollout_provider)
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 273, in _env_runner
    active_episodes)
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 471, in _do_policy_eval
    eval_results[k] = builder.get(v)
  File "/home/ubuntu/anaconda3/envs/flow/lib/python3.5/site-packages/ray/rllib/utils/tf_run_builder.py", line 50, in get
    self.fetches, self.feed_dict))
ValueError: Error fetching: [<tf.Tensor 'av/add:0' shape=(?, 1) dtype=float32>, {'vf_preds': <tf.Tensor 'av/value_function/Reshape:0' shape=(?,) dtype=float32>, 'logits': <tf.Tensor 'av/fc_net/fc_out/BiasAdd:0' shape=(?, 2) dtype=float32>}], feed_dict={<tf.Tensor 'av/obs:0' shape=(?, 35) dtype=float32>: [array([2.39693120e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.09949044e-01, 5.44044067e-01,
       3.36666667e-04, 3.13294233e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.01240008e-02, 2.35141871e-01,
       1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       1.16666667e-01, 0.00000000e+00, 0.00000000e+00, 1.00000000e-01,
       4.66581820e-01, 0.00000000e+00, 0.00000000e+00, 6.44127044e-01,
       4.41738133e-01, 5.85911288e-01, 1.40352344e-01]), array([2.39693120e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.09949044e-01, 5.44044067e-01,
       3.36666667e-04, 3.13294233e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.01240008e-02, 2.35141871e-01,
       1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       1.16666667e-01, 0.00000000e+00, 0.00000000e+00, 1.00000000e-01,
       4.66581820e-01, 0.00000000e+00, 0.00000000e+00, 6.44127044e-01,
       2.39693120e-02, 5.62816347e-01, 3.36666667e-04]), array([3.09949044e-01, 5.44044067e-01, 0.00000000e+00, 0.00000000e+00,
       2.39693120e-02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       3.01240008e-02, 2.35141871e-01, 0.00000000e+00, 0.00000000e+00,
       3.36666667e-04, 3.13294233e-02, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.00000000e-01, 0.00000000e+00, 1.16666667e-01, 0.00000000e+00,
       6.44127044e-01, 0.00000000e+00, 4.66581820e-01, 0.00000000e+00,
       5.44044067e-01, 6.57142857e-01, 2.35141871e-01]), array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.35746177, 0.0257219 ])], <tf.Tensor 'av/action_1:0' shape=(?, 1) dtype=float32>: [array([-0.51782936], dtype=float32), array([1.8761749], dtype=float32), array([3.0323503], dtype=float32), array([1.1178758], dtype=float32)], <tf.Tensor 'av/prev_reward:0' shape=(?,) dtype=float32>: [-0.6722903738907431, -0.6722903738907431, -0.6722903738907431, -0.6722903738907431], <tf.Tensor 'av/PlaceholderWithDefault:0' shape=() dtype=bool>: False}


From /home/ubuntu/.local/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Loading configuration... done.
Success.
 Starting SUMO on port 33187
Loading configuration... done.
...
```

## Versions

- OS: Ubuntu 16.04
- Flow version: 0.4.0, branch `cathywu/flow:grid_avs`
- Flow commit number: 52d136029bfa2232d53e8d80a2374ff988e33b0c

**Comment by cathywu** [comment]
Sorry, this is my bad.
