### ISSUE TITLE
Running num_cpus=1 leads to ray.tune.error.TuneError

### ISSUE THREAD

**Issue by buechelmartin** [flow-project/flow#652]
## Bug Description

For some reason which is not plausible to me, in the rrlib/stablilizing_highway example, Ray is inizialized with:

```
# number of parallel workers
N_CPUS = 1
ray.init(num_cpus=N_CPUS +1, redirect_output=False)
```
For sure, the naming is not ideal, which might be the only problem, if num_cpus needs to be NUM_WORKERS + 1.

But I can find some other misleading logs as described below:

Running the example with the lines above, it leads to the following log, saying it is using 2/2 CPUs :

```
/home/buechel/.conda/envs/flow/bin/python /home/buechel/gitfolders/flowfolder/examples/rllib/stabilizing_highway.py
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-07-18_11-55-07_10129/logs.
Waiting for redis server at 127.0.0.1:45534 to respond...
Waiting for redis server at 127.0.0.1:48576 to respond...
Starting the Plasma object store with 6.674094489000001 GB memory using /dev/shm.
I0718 11:55:07.478278 10148 store.cc:994] Allowing the Plasma store to use up to 6.67409GB of memory.
I0718 11:55:07.478509 10148 store.cc:1024] Starting object store with directory /dev/shm and huge page support disabled

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui.ipynb?token=1181430bc2b37f3a0a1af994c1f9270a5034eef4f9c06e12
======================================================================

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/2 CPUs, 0/1 GPUs
Memory usage on this node: 4.9/16.7 GB

Created LogSyncer for /home/buechel/ray_results/stabilizing_open_network_merges/PPO_WaveAttenuationMergePOEnv-v0_0_2019-07-18_11-55-076byv2ze3 -> 
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 2/2 CPUs, 0/1 GPUs
Memory usage on this node: 4.9/16.7 GB
Result logdir: /home/buechel/ray_results/stabilizing_open_network_merges
RUNNING trials:
 - PPO_WaveAttenuationMergePOEnv-v0_0:	RUNNING
```

If I delete the +1 to
`ray.init(num_cpus=N_CPUS, redirect_output=False)`

the following error occurs:

```
/home/buechel/.conda/envs/flow/bin/python /home/buechel/gitfolders/flowfolder/examples/rllib/stabilizing_highway.py
Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-07-18_12-00-25_10476/logs.
Waiting for redis server at 127.0.0.1:15547 to respond...
Waiting for redis server at 127.0.0.1:35164 to respond...
Starting the Plasma object store with 6.674094489000001 GB memory using /dev/shm.
I0718 12:00:26.320734 10497 store.cc:994] Allowing the Plasma store to use up to 6.67409GB of memory.
I0718 12:00:26.320981 10497 store.cc:1024] Starting object store with directory /dev/shm and huge page support disabled

======================================================================
View the web UI at http://localhost:8888/notebooks/ray_ui.ipynb?token=743fda6774e8dd2f7976efc73eb89b2c053813904d0dd542
======================================================================

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/1 CPUs, 0/1 GPUs
Memory usage on this node: 4.9/16.7 GB

Traceback (most recent call last):
  File "/home/buechel/gitfolders/flowfolder/examples/rllib/stabilizing_highway.py", line 187, in <module>
    "training_iteration": 500,
  File "/home/buechel/.conda/envs/flow/lib/python3.5/site-packages/ray/tune/tune.py", line 109, in run_experiments
    runner.step()
  File "/home/buechel/.conda/envs/flow/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 133, in step
    trial.config)))
ray.tune.error.TuneError: Insufficient cluster resources to launch trial: trial requested 2 CPUs, 0 GPUs but the cluster has only 1 CPUs, 1 GPUs. Pass `queue_trials=True` in ray.tune.run_experiments() or on the command line to queue trials until the cluster scales up. 

You can adjust the resource requests of RLlib agents by setting `num_workers` and other configs. See the DEFAULT_CONFIG defined by each agent for more info.

The config of this agent is: {'clip_rewards': None, 'clip_param': 0.3, 'log_level': 'INFO', 'num_sgd_iter': 10, 'simple_optimizer': False, 'callbacks': {'on_sample_end': None, 'on_episode_start': None, 'on_train_result': None, 'on_episode_step': None, 'on_episode_end': None}, 'vf_loss_coeff': 1.0, 'collect_metrics_timeout': 180, 'gamma': 0.999, 'output': None, 'num_envs_per_worker': 1, 'optimizer': {}, 'sample_batch_size': 200, 'train_batch_size': 37500, 'clip_actions': False, 'preprocessor_pref': 'deepmind', 'num_cpus_for_driver': 1, 'input_evaluation': None, 'kl_coeff': 0.2, 'vf_clip_param': 10.0, 'monitor': False, 'custom_resources_per_worker': {}, 'lr_schedule': None, 'model': {'custom_preprocessor': None, 'framestack': True, 'dim': 84, 'grayscale': False, 'fcnet_hiddens': [100, 50, 25], 'custom_model': None, 'conv_filters': None, 'free_log_std': False, 'channel_major': False, 'conv_activation': 'relu', 'max_seq_len': 20, 'lstm_cell_size': 256, 'zero_mean': True, 'custom_options': {}, 'use_lstm': False, 'squash_to_range': False, 'fcnet_activation': 'tanh', 'lstm_use_prev_action_reward': False}, 'tf_session_args': {'allow_soft_placement': True, 'gpu_options': {'allow_growth': True}, 'inter_op_parallelism_threads': 2, 'log_device_placement': False, 'device_count': {'CPU': 1}, 'intra_op_parallelism_threads': 2}, 'use_gae': True, 'lr': 5e-05, 'num_workers': 1, 'lambda': 0.97, 'entropy_coeff': 0.0, 'observation_filter': 'MeanStdFilter', 'horizon': 750, 'env': 'WaveAttenuationMergePOEnv-v0', 'straggler_mitigation': False, 'input': 'sampler', 'num_cpus_per_worker': 1, 'batch_mode': 'truncate_episodes', 'env_config': {'flow_params': '{\n    "env": {\n        "additional_params": {\n            "max_accel": 1.5,\n            "max_decel": 1.5,\n            "num_rl": 13,\n            "target_velocity": 30\n        },\n        "clip_actions": true,\n        "evaluate": false,\n        "horizon": 750,\n        "sims_per_step": 5,\n        "warmup_steps": 3\n    },\n    "env_name": "WaveAttenuationMergePOEnv",\n    "exp_tag": "stabilizing_open_network_merges",\n    "initial": {\n        "additional_params": {},\n        "bunching": 0,\n        "edges_distribution": "all",\n        "lanes_distribution": Infinity,\n        "min_gap": 0,\n        "perturbation": 0.0,\n        "shuffle": false,\n        "spacing": "uniform",\n        "x0": 0\n    },\n    "net": {\n        "additional_params": {\n            "highway_lanes": 1,\n            "merge_lanes": 1,\n            "merge_length": 300,\n            "post_merge_length": 100,\n            "pre_merge_length": 500,\n            "speed_limit": 30\n        },\n        "inflows": {\n            "_InFlows__flows": [\n                {\n                    "begin": 1,\n                    "departLane": "free",\n                    "departSpeed": 10,\n                    "edge": "inflow_highway",\n                    "end": 2000000.0,\n                    "name": "flow_0",\n                    "vehsPerHour": 1500.0,\n                    "vtype": "human"\n                },\n                {\n                    "begin": 1,\n                    "departLane": "free",\n                    "departSpeed": 10,\n                    "edge": "inflow_highway",\n                    "end": 2000000.0,\n                    "name": "flow_1",\n                    "vehsPerHour": 500.0,\n                    "vtype": "rl"\n                },\n                {\n                    "begin": 1,\n                    "departLane": "free",\n                    "departSpeed": 7.5,\n                    "edge": "inflow_merge",\n                    "end": 2000000.0,\n                    "name": "flow_2",\n                    "vehsPerHour": 100,\n                    "vtype": "human"\n                }\n            ],\n            "num_flows": 3\n        },\n        "no_internal_links": false,\n        "osm_path": null,\n        "template": null\n    },\n    "scenario": "MergeScenario",\n    "sim": {\n        "emission_path": null,\n        "lateral_resolution": null,\n        "no_step_log": true,\n        "num_clients": 1,\n        "overtake_right": false,\n        "port": null,\n        "print_warnings": true,\n        "pxpm": 2,\n        "render": false,\n        "restart_instance": true,\n        "save_render": false,\n        "seed": null,\n        "show_radius": false,\n        "sight_radius": 25,\n        "sim_step": 0.2,\n        "teleport_time": -1\n    },\n    "simulator": "traci",\n    "veh": [\n        {\n            "acceleration_controller": [\n                "IDMController",\n                {\n                    "noise": 0.2\n                }\n            ],\n            "car_following_params": {\n                "controller_params": {\n                    "accel": 1.0,\n                    "carFollowModel": "IDM",\n                    "decel": 1.5,\n                    "impatience": 0.5,\n                    "maxSpeed": 30,\n                    "minGap": 2.5,\n                    "sigma": 0.5,\n                    "speedDev": 0.1,\n                    "speedFactor": 1.0,\n                    "tau": 1.0\n                },\n                "speed_mode": 1\n            },\n            "initial_speed": 0,\n            "lane_change_controller": [\n                "SimLaneChangeController",\n                {}\n            ],\n            "lane_change_params": {\n                "controller_params": {\n                    "laneChangeModel": "LC2013",\n                    "lcCooperative": "1.0",\n                    "lcKeepRight": "1.0",\n                    "lcSpeedGain": "1.0",\n                    "lcStrategic": "1.0"\n                },\n                "lane_change_mode": 512\n            },\n            "num_vehicles": 5,\n            "routing_controller": null,\n            "veh_id": "human"\n        },\n        {\n            "acceleration_controller": [\n                "RLController",\n                {}\n            ],\n            "car_following_params": {\n                "controller_params": {\n                    "accel": 1.0,\n                    "carFollowModel": "IDM",\n                    "decel": 1.5,\n                    "impatience": 0.5,\n                    "maxSpeed": 30,\n                    "minGap": 2.5,\n                    "sigma": 0.5,\n                    "speedDev": 0.1,\n                    "speedFactor": 1.0,\n                    "tau": 1.0\n                },\n                "speed_mode": 1\n            },\n            "initial_speed": 0,\n            "lane_change_controller": [\n                "SimLaneChangeController",\n                {}\n            ],\n            "lane_change_params": {\n                "controller_params": {\n                    "laneChangeModel": "LC2013",\n                    "lcCooperative": "1.0",\n                    "lcKeepRight": "1.0",\n                    "lcSpeedGain": "1.0",\n                    "lcStrategic": "1.0"\n                },\n                "lane_change_mode": 512\n            },\n            "num_vehicles": 0,\n            "routing_controller": null,\n            "veh_id": "rl"\n        }\n    ]\n}', 'run': 'PPO'}, 'output_max_file_size': 67108864, 'multiagent': {'policy_mapping_fn': None, 'policy_graphs': {}, 'policies_to_train': None}, 'kl_target': 0.02, 'sample_async': False, 'sgd_minibatch_size': 128, 'num_gpus_per_worker': 0, 'vf_share_layers': False, 'num_gpus': 0, 'synchronize_filters': True, 'compress_observations': False, 'output_compress_columns': ['obs', 'new_obs'], 'local_evaluator_tf_session_args': {'inter_op_parallelism_threads': 8, 'intra_op_parallelism_threads': 8}}
I0718 12:00:26.563962 10497 store.cc:599] Disconnecting client on fd 10
*** Aborted at 1563444026 (unix time) try "date -d @1563444026" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGTERM (@0x3e8000028ec) received by PID 10495 (TID 0x7f387816c740) from PID 10476; stack trace: ***
    @     0x7f3877d86390 (unknown)
    @     0x7f38770099f3 epoll_wait
    @           0x454698 boost::asio::detail::epoll_reactor::run()
    @           0x455169 boost::asio::detail::scheduler::run()
    @           0x4512d8 main
    @     0x7f3876f22830 __libc_start_main
    @           0x4528f1 (unknown)
I0718 12:00:26.569162 10497 store.cc:599] Disconnecting client on fd 8
I0718 12:00:26.569181 10497 store.cc:599] Disconnecting client on fd 6
I0718 12:00:26.569430 10497 store.cc:599] Disconnecting client on fd 9
```
Obviously, there is a mismatch in detecting the correct number of available CPUs.
Now it said 
Resources requested: 0/1 CPUs, 0/1 GPUs
but later:
Insufficient cluster resources to launch trial: trial requested 2 CPUs, 0 GPUs but the cluster has only 1 CPUs, 1 GPUs.

**Comment by buechelmartin** [comment]
In reality, I have 8 CPUS on my laptop. Running num_cpus=8, I get:

```
Resources requested: 0/8 CPUs, 0/1 GPUs
Memory usage on this node: 5.0/16.7 GB
...
ray.tune.error.TuneError: Insufficient cluster resources to launch trial: trial requested 9 CPUs, 0 GPUs but the cluster has only 8 CPUs, 1 GPUs.
```

The maximum number of workers I seem to get is 6 with num_cpus=7, when it says 
`Resources requested: 7/7 CPUs, 0/1 GPUs`

**Comment by eugenevinitsky** [comment]
So, this isn't exactly a bug, the maximum number of works is your total number of CPUs - 1.

**Comment by eugenevinitsky** [comment]
Additionally, many of the Ray algorithms require num_cpus greater than or equal to 2. We're working on porting in a lighter library than RLlib but in the meantime that should help?

**Comment by buechelmartin** [comment]
Well, Ray not giving back the correct total number of max. available CPUs I would call a bug.

On the Flow side, I feel it is definitely misleading to call that constant N_CPUS and comment it with "# number of parallel workers". Maybe this could reduce some confusion.
