### ISSUE TITLE
Environment reset is broken

### ISSUE THREAD

**Issue by bmwilly** [flow-project/flow#691]
## Bug Description

The environment does not reset properly when `flow.core.experiment.Experiment.run` is called with `num_runs` > 1. 

## Bug Reproduce

File in which the bug occurred: `examples/sumo/bottlenecks.py`

The exact command that you did run that caused the bug:
`python examples/sumo/bottlenecks.py`

## Output Log

```
(traffic-lights) ➜  flow git:(simulation) ✗ python examples/sumo/bottlenecks.py
/Users/brandon/projects/forks/flow/flow/utils/flow_warnings.py:20: UserWarning: The attribute vehsPerHour in InFlows is deprecated, use vehs_per_hour instead.
  dep_from, obj.__class__.__name__, dep_to))
/Users/brandon/projects/forks/flow/flow/utils/flow_warnings.py:20: UserWarning: The attribute departLane in InFlows is deprecated, use depart_lane instead.
  dep_from, obj.__class__.__name__, dep_to))
/Users/brandon/projects/forks/flow/flow/utils/flow_warnings.py:20: UserWarning: The attribute departSpeed in InFlows is deprecated, use depart_speed instead.
  dep_from, obj.__class__.__name__, dep_to))
Loading configuration... done.
Success.
 Retrying in 1 seconds
Could not connect to TraCI server at localhost:53921 [Errno 61] Connection refused
 Retrying in 2 seconds
Could not connect to TraCI server at localhost:53921 [Errno 61] Connection refused
 Retrying in 3 seconds
Could not connect to TraCI server at localhost:53921 [Errno 61] Connection refused
 Retrying in 4 seconds
Loading configuration... done.
**********************************************************
**********************************************************
**********************************************************
WARNING: Inflows will cause computational performance to
significantly decrease after large number of rollouts. In
order to avoid this, set SumoParams(restart_instance=True).
**********************************************************
**********************************************************
**********************************************************
Round 0, return: 847.0800000000135
**********************************************************
**********************************************************
**********************************************************
WARNING: Inflows will cause computational performance to
significantly decrease after large number of rollouts. In
order to avoid this, set SumoParams(restart_instance=True).
**********************************************************
**********************************************************
**********************************************************
Traceback (most recent call last):
  File "examples/sumo/bottlenecks.py", line 202, in <module>
    exp.run(5, 1000)
  File "examples/sumo/bottlenecks.py", line 57, in run
    state = self.env.reset()
  File "/Users/brandon/projects/forks/flow/flow/envs/base_env.py", line 496, in reset
    self.k.update(reset=True)
  File "/Users/brandon/projects/forks/flow/flow/core/kernel/kernel.py", line 100, in update
    self.vehicle.update(reset)
  File "/Users/brandon/projects/forks/flow/flow/core/kernel/vehicle/traci.py", line 138, in update
    if vehicle_obs[veh_id] is None:
KeyError: 'flow_00.231'
```

## Versions

- OS: ? macOS 10.14.6
- Flow version: ? 0.4.1.dev
- Flow commit number: ? 2294c947b441471a968a3f26d95a52d56dafd368

**Comment by bmwilly** [comment]
possibly related: https://github.com/flow-project/flow/issues/491

**Comment by eugenevinitsky** [comment]
Hmmm, this is bad. Lets see if we can reproduce this and figure this out.

**Comment by eugenevinitsky** [comment]
Hi @bmwilly, I can't reproduce this. Are you running Flow greater than 0.3.1?

**Comment by eugenevinitsky** [comment]
if you make a pull request I can try and reproduce there?

**Comment by bmwilly** [comment]
@eugenevinitsky yep, I'm running Flow 0.4.1.dev. There's no PR to open since I've installed Flow with `pip install -e .` on a commit that lives on master (2294c94).

**Comment by eugenevinitsky** [comment]
Yeah, okay that's a recent enough commit that I should be able to reproduce it. Let me give it another go.

**Comment by kevin-thankyou-lin** [comment]
Hi @bmwilly the issue doesn't exist on master, so we recommend that you could update to master.
