### ISSUE TITLE
Error when running multiagent_highway.py

### ISSUE THREAD

**Issue by nanxintin** [flow-project/flow#739]
When running the new version of flow(0.5.0.dev), there is an error: 

Traceback (most recent call last):
  File "/home/shaokun/projects/py3.5-ray0.7.3/lib/python3.5/site-packages/ray/tune/trial_runner.py", line 498, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/shaokun/projects/py3.5-ray0.7.3/lib/python3.5/site-packages/ray/tune/ray_trial_executor.py", line 342, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/shaokun/projects/py3.5-ray0.7.3/lib/python3.5/site-packages/ray/worker.py", line 2247, in get
    raise value
ray.exceptions.RayTaskError: ray_PPO:train() (pid=6330, host=sk)
  File "/home/shaokun/projects/py3.5-ray0.7.3/lib/python3.5/site-packages/ray/rllib/agents/trainer.py", line 369, in train
    raise e
  File "/home/shaokun/projects/py3.5-ray0.7.3/lib/python3.5/site-packages/ray/rllib/agents/trainer.py", line 358, in train
    result = Trainable.train(self)
  File "/home/shaokun/projects/py3.5-ray0.7.3/lib/python3.5/site-packages/ray/tune/trainable.py", line 171, in train
    result = self._train()
  File "/home/shaokun/projects/py3.5-ray0.7.3/lib/python3.5/site-packages/ray/rllib/agents/trainer_template.py", line 126, in _train
    fetches = self.optimizer.step()
  File "/home/shaokun/projects/py3.5-ray0.7.3/lib/python3.5/site-packages/ray/rllib/optimizers/sync_samples_optimizer.py", line 52, in step
    for e in self.workers.remote_workers()
  File "/home/shaokun/projects/py3.5-ray0.7.3/lib/python3.5/site-packages/ray/rllib/utils/memory.py", line 33, in ray_get_and_free
    result = ray.get(object_ids)
ray.exceptions.RayTaskError: ray_RolloutWorker:sample() (pid=6329, host=sk)
  File "/home/shaokun/projects/py3.5-ray0.7.3/lib/python3.5/site-packages/ray/rllib/evaluation/rollout_worker.py", line 453, in sample
    batches = [self.input_reader.next()]
  File "/home/shaokun/projects/py3.5-ray0.7.3/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 56, in next
    batches = [self.get_data()]
  File "/home/shaokun/projects/py3.5-ray0.7.3/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 97, in get_data
    item = next(self.rollout_provider)
  File "/home/shaokun/projects/py3.5-ray0.7.3/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 313, in _env_runner
    soft_horizon)
  File "/home/shaokun/projects/py3.5-ray0.7.3/lib/python3.5/site-packages/ray/rllib/evaluation/sampler.py", line 451, in _process_observations
    episode.batch_builder.check_missing_dones()
  File "/home/shaokun/projects/py3.5-ray0.7.3/lib/python3.5/site-packages/ray/rllib/evaluation/sample_batch_builder.py", line 187, in check_missing_dones
    "Please ensure that you include the last observations "
ValueError: The environment terminated for all agents, but we still don't have a last observation for agent rl_highway_inflow_1.1 (policy av). Please ensure that you include the last observations of all live agents when setting '__all__' done to True.

**Comment by eugenevinitsky** [comment]
Ooh, good catch. This is going to be a bug with the most recent rllib version. We will try to fix this quickly. This occurs when there are crashes, you can temporarily fix this by removing the check that sets done = True if there is a crash.

**Comment by eugenevinitsky** [comment]
Hi @nanxintin we currently have a developer working to fix this now. Sorry for the delay.

**Comment by nanxintin** [comment]
@eugenevinitsky  Thanks for your work.

**Comment by nanxintin** [comment]
Hi @eugenevinitsky , I have another question about the multiagent_highway example. At present, we use one PPO policy shared among all the agents to control the acceleration of each vehicle. Can we use two or more different policies during training ? In other words, can we apply different policies for each vehicle or part vehicles ? If so, could you give me some suggestions to achieve that ? Thanks.

**Comment by eugenevinitsky** [comment]
Oh man, I'm sorry I missed this. This bug is resolved in #767. As for your other question, you can have as many policies as you want! You just need to instantiate an additional policy and add it to the policy graphs.
