### ISSUE TITLE
Observation outside expected value range when executing multiAgentRL_Ring.py

### ISSUE THREAD

**Issue by chinmaySwami** [flow-project/flow#760]
Hi,

When executing the multiAgentRL_Ring.py following error is being received.
ray.tune.error.TuneError: ('Trials did not complete', [PPO_MultiWaveAttenuationPOEnv-v0_0_lr=1e-05])

reason for that seems to be 
ValueError: ('Observation outside expected value range', Box(3,), array([ 0.19800116, -0.05078842,  0.04750252]))

**Comment by eugenevinitsky** [comment]
Thanks for pointing this out. I will have a PR up in 5 minutes.

**Comment by eugenevinitsky** [comment]
If you pull master this bug should be resolved.

**Comment by eugenevinitsky** [comment]
Let me know if it's resolved and I will close the issue. Otherwise, let me know what's happening!

**Comment by chinmaySwami** [comment]
Hi,

I carried out the changes that you did to file wave_attenuation.py.  However, even though the code terminated its still giving the same error in the log. 
But let me run it for multiple iterations and get back to you.

**Comment by eugenevinitsky** [comment]
The exact same bug?

**Comment by chinmaySwami** [comment]
Hi,

I ran into same error both with same.
'Training_iteration':1 : The code threw similar error but did execute successfully and a check_point was created.
'Training_iteration':200 : Same bug was observed as reported earlier
'Training_iteration':200, RL agents : 2 : Same bug was observed as reported earlier

**Comment by eugenevinitsky** [comment]
See, I'm just confused because the Box now has a low value of -1 and so shouldn't error for values being < 0. Can you post the error you're seeing now?

**Comment by chinmaySwami** [comment]
Hi,

This is from the error file generated:

Traceback (most recent call last):
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 498, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 342, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/worker.py", line 2247, in get
    raise value
ray.exceptions.RayTaskError: ^[[36mray_PPO:train()^[[39m (pid=27633, host=jkang1)
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 369, in train
    raise e
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 358, in train
    result = Trainable.train(self)
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/trainable.py", line 171, in train
    result = self._train()
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 126, in _train
    fetches = self.optimizer.step()
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/optimizers/sync_samples_optimizer.py", line 52, in step
    for e in self.workers.remote_workers()
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/utils/memory.py", line 33, in ray_get_and_free
    result = ray.get(object_ids)
ray.exceptions.RayTaskError: ^[[36mray_RolloutWorker:sample()^[[39m (pid=27632, host=jkang1)
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 453, in sample
    batches = [self.input_reader.next()]
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 56, in next
    batches = [self.get_data()]
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 97, in get_data
    item = next(self.rollout_provider)
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 313, in _env_runner
    soft_horizon)
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 401, in _process_observations
    policy_id).transform(raw_obs)
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/models/preprocessors.py", line 166, in transform
    self.check_shape(observation)
  File "/home/jiyeon/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/models/preprocessors.py", line 61, in check_shape
    self._obs_space, observation)
ValueError: ('Observation outside expected value range', Box(3,), array([0.05752458, 0.        , 4.34782609]))

Thr program runs fine for 1 iteration ie even after giving error[same as this] it does create a checkpoint. However, for more than 1 iteration it just fails.
Above error is for 10 iterations.

**Comment by eugenevinitsky** [comment]
@AboudyKreidieh pointed out that there's an additional error here where we divide the headway by 230 but your network is of length 1000. I'll push up a PR shortly and point you to it.

**Comment by eugenevinitsky** [comment]
As a quick hack you can go into the env and in get_state increase the normalization constants so you're dividing by 1000.

**Comment by chinmaySwami** [comment]
Hello Eugene,

Apologies for the delay in response. I don't understand. My network is of length 1000 ? I am using the same code as in the tutorial. The only thing I changed is training iteration. So the length of ring is  230 as per the code

**Comment by ctc199625** [comment]
Hello，Professors：
        I also encountered this type of error. When I run the figure-eight in rllib, I modified the number and initialization location of the RL-agent car. After running for a while, sometimes the system will generate the corresponding checkpoint, but most of the time there will be an error log in ray-results.Do you have any good suggestions or solutions?  @chinmaySwami  @eugenevinitsky 

**This is from the error file generated:**
Traceback (most recent call last):
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 506, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 347, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/worker.py", line 2349, in get
    raise value
ray.exceptions.RayTaskError: [36mray_PPO:train()[39m (pid=13985, host=xiaochao-virtual-machine)
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 417, in train
    raise e
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/agents/trainer.py", line 406, in train
    result = Trainable.train(self)
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/tune/trainable.py", line 176, in train
    result = self._train()
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/agents/trainer_template.py", line 129, in _train
    fetches = self.optimizer.step()
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/optimizers/multi_gpu_optimizer.py", line 140, in step
    self.num_envs_per_worker, self.train_batch_size)
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/optimizers/rollout.py", line 29, in collect_samples
    next_sample = ray_get_and_free(fut_sample)
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/utils/memory.py", line 33, in ray_get_and_free
    result = ray.get(object_ids)
ray.exceptions.RayTaskError: [36mray_RolloutWorker:sample()[39m (pid=13992, host=xiaochao-virtual-machine)
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 469, in sample
    batches = [self.input_reader.next()]
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 56, in next
    batches = [self.get_data()]
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 99, in get_data
    item = next(self.rollout_provider)
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 319, in _env_runner
    soft_horizon, no_done_at_end)
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 407, in _process_observations
    policy_id).transform(raw_obs)
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/models/preprocessors.py", line 170, in transform
    self.check_shape(observation)
  File "/home/xiaochao/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/models/preprocessors.py", line 65, in check_shape
    self._obs_space, observation)
ValueError: ('Observation outside expected value range', Box(16,), array([ 4.51649060e-01,  4.46476508e-01,  3.79074621e-01, -3.57913941e+07,
        3.13034091e-01,  4.72529930e-01,  3.94568009e-01,  1.12943324e-01,
        2.64957647e-01,  3.44459339e-01,  4.94487546e-01,  0.00000000e+00,
        6.19711688e-01,  8.75877236e-01,  9.82541153e-01,  8.09446112e-02]))

**Comment by eugenevinitsky** [comment]
Oh I see what happens, there's a crash in this environment and it's not caught appropriately. Thanks for catching this, I'll push a fix shortly.

**Comment by ctc199625** [comment]
Thank you very much for your letter. Your answer is very helpful to me. I will continue my work. @eugenevinitsky
