### ISSUE TITLE
Still don't have a last observation for agent rl_highway_inflow_1.0 (policy av)

### ISSUE THREAD

**Issue by ZJP1993** [flow-project/flow#773]
**#Bug Description**

In order to the performance of multi-agent algorithm of flow, I ran /flow/examples/rllib/multiagent_exps/multiagent_highway.py. I expected that there are no error report and I can plot reward value curve by tensorboard.

**## Bug Reproduce**

File in which the bug occurred: `/flow/examples/rllib/multiagent_exps/multiagent_highway.py.`

The exact command that you did run that caused the bug:
`python multiagent_highway.py`

**## Output Log**

**Full error output log:**
Full error output log is too long to paste here(about 160 pages in Microsoft Word). I have to paste only a section of output log.

Loading configuration... done.
Success.
Loading configuration... done.
2019-11-05 21:54:11,459	INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-11-05_21-54-11_459429_28460/logs.
2019-11-05 21:54:11,569	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:45583 to respond...
2019-11-05 21:54:11,683	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:56563 to respond...
2019-11-05 21:54:11,684	INFO services.py:809 -- Starting Redis shard with 6.73 GB max memory.
2019-11-05 21:54:11,707	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2019-11-05_21-54-11_459429_28460/logs.
2019-11-05 21:54:11,707	INFO services.py:1475 -- Starting the Plasma object store with 10.09 GB memory using /dev/shm.
2019-11-05 21:54:11,810	INFO trial_runner.py:176 -- Starting a new experiment.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/12 CPUs, 0/2 GPUs
Memory usage on this node: 7.4/33.6 GB

2019-11-05 21:54:11,882	WARNING signature.py:108 -- The function with_updates has a **kwargs argument, which is currently not supported.
2019-11-05 21:54:12,003	ERROR log_sync.py:34 -- Log sync requires cluster to be setup with `ray up`.
2019-11-05 21:54:12,298	WARNING worker.py:352 -- WARNING: Falling back to serializing objects of type <class 'numpy.dtype'> by using pickle. This may be inefficient.
2019-11-05 21:54:12,363	WARNING worker.py:352 -- WARNING: Falling back to serializing objects of type <class 'mtrand.RandomState'> by using pickle. This may be inefficient.
2019-11-05 21:54:12,445	WARNING util.py:145 -- The `start_trial` operation took 0.5827431678771973 seconds to complete, which may be a performance bottleneck.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 12/12 CPUs, 0/2 GPUs
Memory usage on this node: 7.7/33.6 GB
Result logdir: /home/dl_e/ray_results/multiagent_highway
Number of trials: 1 ({'RUNNING': 1})
RUNNING trials:
 - PPO_MultiAgentHighwayPOEnv-v0_0_lr=1e-05:	RUNNING
...
...
...

(pid=28724) Warning: Vehicle 'rl_highway_inflow_1.6' performs emergency braking with decel=-10.61 wished=4.50 severity=1.36, time=57.20.
(pid=28730) Warning: Vehicle 'idm_highway_inflow_00.25' performs emergency braking with decel=-9.00 wished=4.50 severity=1.00, time=58.60.
2019-11-05 21:54:52,025	ERROR worker.py:1654 -- Possible unhandled error from worker: ray_RolloutWorker:sample() (pid=28514, host=611dabai)
  File "/home/dl_e/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/rollout_worker.py", line 453, in sample
    batches = [self.input_reader.next()]
  File "/home/dl_e/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 56, in next
    batches = [self.get_data()]
  File "/home/dl_e/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 97, in get_data
    item = next(self.rollout_provider)
  File "/home/dl_e/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 313, in _env_runner
    soft_horizon)
  File "/home/dl_e/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sampler.py", line 451, in _process_observations
    episode.batch_builder.check_missing_dones()
  File "/home/dl_e/anaconda3/envs/flow/lib/python3.6/site-packages/ray/rllib/evaluation/sample_batch_builder.py", line 187, in check_missing_dones
    "Please ensure that you include the last observations "
ValueError: The environment terminated for all agents, but we still don't have a last observation for agent rl_highway_inflow_1.0 (policy av). Please ensure that you include the last observations of all live agents when setting '__all__' done to True.

...
...
...

(pid=30648) 2019-11-05 22:19:00,877	INFO trainer.py:366 -- Worker crashed during call to train(). To attempt to continue training without the failed worker, set `'ignore_worker_failures': True`.
2019-11-05 22:19:01,053	WARNING util.py:145 -- The `experiment_checkpoint` operation took 0.16717910766601562 seconds to complete, which may be a performance bottleneck.
== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/12 CPUs, 0/2 GPUs
Memory usage on this node: 11.8/33.6 GB
Result logdir: /home/dl_e/ray_results/multiagent_highway
Number of trials: 1 ({'ERROR': 1})
ERROR trials:
 - PPO_MultiAgentHighwayPOEnv-v0_0_lr=1e-05:	ERROR, 4 failures: /home/dl_e/ray_results/multiagent_highway/PPO_MultiAgentHighwayPOEnv-v0_0_lr=1e-05_2019-11-05_21-54-1187wkw4dz/error_2019-11-05_22-19-00.txt, [12 CPUs, 0 GPUs], [pid=29761], 1007 s, 1 iter, 30800 ts, 5.52e+03 rew

== Status ==
Using FIFO scheduling algorithm.
Resources requested: 0/12 CPUs, 0/2 GPUs
Memory usage on this node: 11.8/33.6 GB
Result logdir: /home/dl_e/ray_results/multiagent_highway
Number of trials: 1 ({'ERROR': 1})
ERROR trials:
 - PPO_MultiAgentHighwayPOEnv-v0_0_lr=1e-05:	ERROR, 4 failures: /home/dl_e/ray_results/multiagent_highway/PPO_MultiAgentHighwayPOEnv-v0_0_lr=1e-05_2019-11-05_21-54-1187wkw4dz/error_2019-11-05_22-19-00.txt, [12 CPUs, 0 GPUs], [pid=29761], 1007 s, 1 iter, 30800 ts, 5.52e+03 rew

Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/dl_e/anaconda3/envs/flow/lib/python3.6/site-packages/ray/worker.py", line 1551, in custom_excepthook
    {"exception": error_message})
  File "/home/dl_e/anaconda3/envs/flow/lib/python3.6/site-packages/redis/client.py", line 2011, in hmset
    return self.execute_command('HMSET', name, *items)
  File "/home/dl_e/anaconda3/envs/flow/lib/python3.6/site-packages/redis/client.py", line 667, in execute_command
    connection.send_command(*args)
  File "/home/dl_e/anaconda3/envs/flow/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/dl_e/anaconda3/envs/flow/lib/python3.6/site-packages/redis/connection.py", line 650, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/home/dl_e/anaconda3/envs/flow/lib/python3.6/site-packages/redis/connection.py", line 105, in encode
    def encode(self, value):
RecursionError: maximum recursion depth exceeded

## Versions

- OS: Ubuntu 16.04
- Flow version: 
Python 3.6.7 | packaged by conda-forge | (default, Jul  2 2019, 02:18:42) 
[GCC 7.3.0] on linux
>>> import flow
>>> print(flow.__version__)
0.5.0.dev

**Comment by eugenevinitsky** [comment]
Can you give the git hash of your version? As in, are you on master? We pushed a bug fix that (hopefully) fixed this a week or so back.

**Comment by ZJP1993** [comment]
Thank you for your prompt reply.When I try to get the git hash, some errors occur as following.

(flow) dl_e@611dabai:/media/dl_e/17EF48822800F82E/zjp/code/flow/examples/rllib/multiagent_exps$ git rev-parse HEAD
fatal: Not a git repository (or any parent up to mount point /media/dl_e/17EF48822800F82E)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by eugenevinitsky** [comment]
Uh, just stop to the outer directory and run `git log` and the first commit that shows up is the hash

**Comment by ZJP1993** [comment]
I find that I have not initialized the repository yet.I run the command "git init" in /media/dl_e/17EF48822800F82E/zjp/code/flow and then type "git log".A error output —— your branch has no submission. Maybe I have to run /flow/examples/rllib/multiagent_exps/multiagent_highway.py again and get the git hash.
