### ISSUE TITLE
error while loading shared libraries:

### ISSUE THREAD

**Issue by SHITIANYU-hue** [flow-project/flow#826]
I run:
python examples/train.py singleagent_ring --rl_trainer Stable-Baselines

But got this following error:
netconvert: error while loading shared libraries: libproj.so.12: cannot open shared object file: No such file or directory
Error during start: [Errno 2] No such file or directory: '/flow/flow/core/kernel/network/debug/cfg/stabilizing_the_ring_20200206-1514311581002071.151353.net.xml'
Retrying in 1 seconds...
Error during start: [Errno 2] No such file or directory: '/flow/flow/core/kernel/network/debug/cfg/stabilizing_the_ring_20200206-1514311581002071.151353.net.xml'
Retrying in 1 seconds...
Error during start: [Errno 2] No such file or directory: '/flow/flow/core/kernel/network/debug/cfg/stabilizing_the_ring_20200206-1514311581002071.151353.net.xml'
Retrying in 1 seconds...
Error during start: [Errno 2] No such file or directory: '/flow/flow/core/kernel/network/debug/cfg/stabilizing_the_ring_20200206-1514311581002071.151353.net.xml'
Retrying in 1 seconds...
Error during start: [Errno 2] No such file or directory: '/flow/flow/core/kernel/network/debug/cfg/stabilizing_the_ring_20200206-1514311581002071.151353.net.xml'
Retrying in 1 seconds...
Error during start: [Errno 2] No such file or directory: '/flow/flow/core/kernel/network/debug/cfg/stabilizing_the_ring_20200206-1514311581002071.151353.net.xml'
Retrying in 1 seconds...
Error during start: [Errno 2] No such file or directory: '/flow/flow/core/kernel/network/debug/cfg/stabilizing_the_ring_20200206-1514311581002071.151353.net.xml'
Retrying in 1 seconds...
Error during start: [Errno 2] No such file or directory: '/flow/flow/core/kernel/network/debug/cfg/stabilizing_the_ring_20200206-1514311581002071.151353.net.xml'
Retrying in 1 seconds...
Error during start: [Errno 2] No such file or directory: '/flow/flow/core/kernel/network/debug/cfg/stabilizing_the_ring_20200206-1514311581002071.151353.net.xml'
Retrying in 1 seconds...
Error during start: [Errno 2] No such file or directory: '/flow/flow/core/kernel/network/debug/cfg/stabilizing_the_ring_20200206-1514311581002071.151353.net.xml'
Retrying in 1 seconds...
Traceback (most recent call last):
  File "examples/train.py", line 227, in <module>
    model = run_model_stablebaseline(flow_params, flags.num_cpus, flags.rollout_size, flags.num_steps)
  File "examples/train.py", line 91, in run_model_stablebaseline
    constructor = env_constructor(params=flow_params, version=0)()
  File "/flow/flow/utils/registry.py", line 130, in create_env
    return gym.envs.make(env_name)
  File "/opt/conda/lib/python3.7/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/gym/envs/registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/gym/envs/registration.py", line 73, in make
    env = cls(**_kwargs)
  File "/flow/flow/envs/ring/wave_attenuation.py", line 87, in __init__
    super().__init__(env_params, sim_params, network, simulator)
  File "/flow/flow/envs/base.py", line 160, in __init__
    self.k.network.generate_network(self.network)
  File "/flow/flow/core/kernel/network/traci.py", line 146, in generate_network
    connections
  File "/flow/flow/core/kernel/network/traci.py", line 531, in generate_net
    raise error
TypeError: exceptions must derive from BaseException

**Comment by pengyuan-zhou** [comment]
same

**Comment by pengyuan-zhou** [comment]
Ok, met this error and now solved.
Try these: 

- add sumo to PYTHONPATH
- install/load jasper and netCDF pkgs
