### ISSUE TITLE
Keyerror

### ISSUE THREAD

**Issue by pengyuan-zhou** [flow-project/flow#984]
Hi,
I met with **KeyError: 'idm_x'** (x being a number) in both _h-baslines_ and branch _maddpg_ testing with `singleagent_traffic_light_grid`, like this:
```
Traceback (most recent call last):
  File "experiments/run_fcnet.py", line 135, in <module>
    'data/fcnet'
  File "experiments/run_fcnet.py", line 123, in main
    initial_exploration_steps=args.initial_exploration_steps,
  File "experiments/run_fcnet.py", line 72, in run_exp
    seed=seed,
  File "/home/pengzhou/git/h-baselines/hbaselines/algorithms/off_policy.py", line 668, in learn
    random_actions=True)
  File "/home/pengzhou/git/h-baselines/hbaselines/algorithms/off_policy.py", line 815, in _collect_samples
    for env_num in range(n_steps)
  File "/home/pengzhou/miniconda3/envs/h-baselines/lib/python3.6/site-packages/ray/worker.py", line 1457, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(KeyError): ray::Sampler.collect_sample() (pid=24270, ip=192.168.0.109)
  File "python/ray/_raylet.pyx", line 636, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 619, in ray._raylet.execute_task.function_executor
  File "/home/pengzhou/git/h-baselines/hbaselines/utils/sampler.py", line 157, in collect_sample
    reset_obs = self.env.reset()
  File "/home/pengzhou/git/h-baselines/hbaselines/envs/mixed_autonomy/core.py", line 114, in reset
    obs = self.wrapped_env.reset()
  File "/home/pengzhou/git/flow/flow/envs/base.py", line 503, in reset
    self.setup_initial_state()
  File "/home/pengzhou/git/flow/flow/envs/base.py", line 295, in setup_initial_state
    type_id = self.k.vehicle.get_type(veh_id)
  File "/home/pengzhou/git/flow/flow/core/kernel/vehicle/traci.py", line 456, in get_type
    return self.__vehicles[veh_id]["type"]
KeyError: 'idm_4'
```
The error pops up after the test runs for one minute or so, and doesn't appear in "ring" test.
Could it be traffic_light_grid require some dedicate modified codes?

Thank you.
BR

**Comment by Antonio-Dominguez** [comment]
Hi! I had the exact same error when adding inflows to my network. Could you fix this? if yes, how?

**Comment by pengyuan-zhou** [comment]
> Hi! I had the exact same error when adding inflows to my network. Could you fix this? if yes, how?

Hi, I haven't followed up since then, maybe the recent code updates have solved that?
